### ISSUE TITLE
Refactor test routine

### ISSUE THREAD

**Issue by FabianHofmann** [pz-max/pypsa-africa#1052]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Problem Statement

Currently the test routine uses nested snakemake calls where snakemake is called via a bash command in the Snakefile. This architecture omits error streams and snakemake runs that fail are not reported as such, see https://github.com/pypsa-meets-earth/pypsa-earth/actions/runs/9667460555/job/26669336528#step:9:1739.

## Suggestion

I would propose to execute `snakemake` in the GH workflow and optionally keep the commands in a common file for easy local execution, like https://github.com/PyPSA/pypsa-eur/blob/master/test.sh

I would as well propose to collect all workflow CI's in one yaml that uses a `matrix` entry for setting the operation systems.

**Comment by davide-f** [comment]
Wow!

That is a quite big bug! Thanks for reporting.
Indeed this shouldn't be difficult as that was our previous configuration

**Comment by ekatef** [comment]
> Wow!
> 
> That is a quite big bug! Thanks for reporting. Indeed this shouldn't be difficult as that was our previous configuration

If I recall well, that has been not a bug but a natural delay due to using cached environment... In any case, testing has been changed by #1086, while using `matrix` environment implemented by #1183 and #1210. I wonder if we have any points to add here?

**Comment by FabianHofmann** [comment]
hey @ekatef, thanks for pointing this out. It was already solved through the merge, we can close this.
