### ISSUE TITLE
Missing shared_cutouts in tutorial

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#1054]
## Describe the feature you'd like to see

In the tutorial config, we miss the run->shared_cutouts field

see:
https://github.com/pypsa-meets-earth/pypsa-earth/blob/c1d4b993dc52d1f22a46efab983bcef5289afb95/config.tutorial.yaml#L37

with respect to this:
https://github.com/pypsa-meets-earth/pypsa-earth/blob/c1d4b993dc52d1f22a46efab983bcef5289afb95/config.default.yaml#L27-L31

This is a good first issue for anyone

**Comment by ekatef** [comment]
Hello @davide-f, thanks for flagging this! For now I think it has been covered with the incremental config update, right?
