### ISSUE TITLE
SVD did not converge

### ISSUE THREAD

**Issue by Abdul-Karim786** [pz-max/pypsa-africa#1059]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug
Dear pypsa community, I executed the workflow of pypsa-earth to optimize a model with 27760526 rows, 13193583 columns and 56723007 nonzeros. Optimization has been done with gurobi academic solvers in 226 iterations with optimal objective 4.18049373e+09 in approximately 5 hours. But after successful optimization, a bug is appeared  "numpy.linalg.LinAlgError: SVD did not converge".

## Error Message

INFO:pypsa.linopf:Solve linear problem using Gurobi solver
INFO:pypsa.linopf:Optimization successful. Objective value: 4.18e+09
ERROR:_helpers:An error happened in module 'C:\\Users\\PyPSA\\miniconda3\\envs\\pypsa-earth\\lib\\site-packages\\numpy\\linalg\\linalg.py', function '_raise_linalgerror_svd_nonconvergence': SVD did not converge
Traceback (most recent call last):
  File "E:\PyPSA\PyPSA-PAK\Default\pypsa-earth\.snakemake\shadow\tmp3ecfjyr9\.snakemake\scripts\tmpplgi_rp0.solve_network.py", line 574, in <module>
    n = solve_network(
  File "E:\PyPSA\PyPSA-PAK\Default\pypsa-earth\.snakemake\shadow\tmp3ecfjyr9\.snakemake\scripts\tmpplgi_rp0.solve_network.py", line 526, in solve_network
    network_lopf(
  File "C:\Users\PyPSA\miniconda3\envs\pypsa-earth\lib\site-packages\pypsa\linopf.py", line 1610, in network_lopf
    assign_solution(
  File "C:\Users\PyPSA\miniconda3\envs\pypsa-earth\lib\site-packages\pypsa\linopf.py", line 1437, in assign_solution
    [v_ang_for_(sub) for sub in n.sub_networks.obj], axis=1
  File "C:\Users\PyPSA\miniconda3\envs\pypsa-earth\lib\site-packages\pypsa\linopf.py", line 1437, in <listcomp>
    [v_ang_for_(sub) for sub in n.sub_networks.obj], axis=1
  File "C:\Users\PyPSA\miniconda3\envs\pypsa-earth\lib\site-packages\pypsa\linopf.py", line 1432, in v_ang_for_
    Z = pd.DataFrame(np.linalg.pinv((sub.B).todense()), buses_i, buses_i)
  File "C:\Users\PyPSA\miniconda3\envs\pypsa-earth\lib\site-packages\numpy\linalg\linalg.py", line 2022, in pinv
    u, s, vt = svd(a, full_matrices=False, hermitian=hermitian)
  File "C:\Users\PyPSA\miniconda3\envs\pypsa-earth\lib\site-packages\numpy\linalg\linalg.py", line 1681, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
  File "C:\Users\PyPSA\miniconda3\envs\pypsa-earth\lib\site-packages\numpy\linalg\linalg.py", line 121, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge

```bash
<paste here>
```

**Comment by Abdul-Karim786** [comment]
i have executed it with different configuration settings, i have noticed when I run workflow with setting true augmented line connection I am getting a similar type of error. Without the augmented line, it's working well.

**Comment by ekatef** [comment]
Thanks a lot for reporting the issue @Abdul-Karim786. That is really helpful to understand what is going on with the model.

Could you please provide a bit more input, sharing your configuration file and, if possible, a plot of the network?

**Comment by Abdul-Karim786** [comment]
These files are with true augmented line connection. 
![Screenshot 2024-07-10 140009](https://github.com/pypsa-meets-earth/pypsa-earth/assets/141351480/1fb41cfd-6108-4458-800d-14210fcca5e0)
. The comment section does not support the .yaml file so, I attach the text file.
[config.txt](https://github.com/user-attachments/files/16158495/config.txt)

**Comment by ekatef** [comment]
> These files are with true augmented line connection. ![Screenshot 2024-07-10 140009](https://private-user-images.githubusercontent.com/141351480/347337755-1fb41cfd-6108-4458-800d-14210fcca5e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDUzMDIsIm5iZiI6MTcyMDYwNTAwMiwicGF0aCI6Ii8xNDEzNTE0ODAvMzQ3MzM3NzU1LTFmYjQxY2ZkLTYxMDgtNDQ1OC04MDBkLTE0MjEwZmNjYTVlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQwOTUwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWM2MjM2ZTRlYmFjYzMxYmY1MGU2MTM0MjMxMDJlMTk5ZDdhY2VlZTIzN2E2YTZmMGNhNjhhNzY1ZDY0YzlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hXOrYvjZnMimOGJ5eIfXOgTEWaPNYi3iRk7rorruwxg) . The comment section does not support the .yaml file so, I attach the text file. [config.txt](https://github.com/user-attachments/files/16158495/config.txt)

Thanks a lot. The configuration file looks good.

Regarding augmentation of the network, it looks like that there have been three DC-links added as a result of augmentation, correct? Could you also clarify what is the reason of using the augmentation? Originally, it has been developed to connect the remote areas to the grid, while in your case the grid seems to be still well interconnected.

**Comment by Abdul-Karim786** [comment]
Yes, the above network is the result of augmentation. I am exploring the pypsa-earth in every aspect of Pakistan's modeling that's why I am going with different settings to understand pypsa-earth very well.

**Comment by ekatef** [comment]
> Yes, the above network is the result of augmentation. I am exploring the pypsa-earth in every aspect of Pakistan's modeling that's why I am going with different settings to understand pypsa-earth very well.

Thank you for the clarification. To my understanding, augmentation may not be needed to build a power model for Pakistan, as national system seems still to be well interconnected. 

If there are any imperfect data in the network topology, that can be corrected using options to drop isolated nodes (if any), or merge them into the network. If isolated networks present in the system, it is possible to merge them into a backbone network. The following config parameters can be used to control this functionality:

https://github.com/pypsa-meets-earth/pypsa-earth/blob/e3aefd4ae065fa31244ed20ec23ad6129789437b/config.default.yaml#L66-L67

Regarding the issue you reported, it's clearly a bug. I suspect, it is caused by a way in which are defined electrical parameters of the new DC lines introduced during augmentation. Thanks to reporting it and happy to receive fixes for that.

**Comment by Abdul-Karim786** [comment]
> > Yes, the above network is the result of augmentation. I am exploring the pypsa-earth in every aspect of Pakistan's modeling that's why I am going with different settings to understand pypsa-earth very well.
> 
> Thank you for the clarification. To my understanding, augmentation may not be needed to build a power model for Pakistan, as national system seems still to be well interconnected.
> 
> If there are any imperfect data in the network topology, that can be corrected using options to drop isolated nodes (if any), or merge them into the network. If isolated networks present in the system, it is possible to merge them into a backbone network. The following config parameters can be used to control this functionality:
> 
> https://github.com/pypsa-meets-earth/pypsa-earth/blob/e3aefd4ae065fa31244ed20ec23ad6129789437b/config.default.yaml#L66-L67
> 
> Regarding the issue you reported, it's clearly a bug. I suspect, it is caused by a way in which are defined electrical parameters of the new DC lines introduced during augmentation. Thanks to reporting it and happy to receive fixes for that.

Pakistan network is well interconnected so, I agree with you that there is no need for augmentation in Pakistan's case.

**Comment by Abdul-Karim786** [comment]
> > > Yes, the above network is the result of augmentation. I am exploring the pypsa-earth in every aspect of Pakistan's modeling that's why I am going with different settings to understand pypsa-earth very well.
> > 
> > 
> > Thank you for the clarification. To my understanding, augmentation may not be needed to build a power model for Pakistan, as national system seems still to be well interconnected.
> > If there are any imperfect data in the network topology, that can be corrected using options to drop isolated nodes (if any), or merge them into the network. If isolated networks present in the system, it is possible to merge them into a backbone network. The following config parameters can be used to control this functionality:
> > https://github.com/pypsa-meets-earth/pypsa-earth/blob/e3aefd4ae065fa31244ed20ec23ad6129789437b/config.default.yaml#L66-L67
> > 
> > Regarding the issue you reported, it's clearly a bug. I suspect, it is caused by a way in which are defined electrical parameters of the new DC lines introduced during augmentation. Thanks to reporting it and happy to receive fixes for that.
> 
> Pakistan network is well interconnected so, I agree with you that there is no need for augmentation in Pakistan's case.



> > > Yes, the above network is the result of augmentation. I am exploring the pypsa-earth in every aspect of Pakistan's modeling that's why I am going with different settings to understand pypsa-earth very well.
> > 
> > 
> > Thank you for the clarification. To my understanding, augmentation may not be needed to build a power model for Pakistan, as national system seems still to be well interconnected.
> > If there are any imperfect data in the network topology, that can be corrected using options to drop isolated nodes (if any), or merge them into the network. If isolated networks present in the system, it is possible to merge them into a backbone network. The following config parameters can be used to control this functionality:
> > https://github.com/pypsa-meets-earth/pypsa-earth/blob/e3aefd4ae065fa31244ed20ec23ad6129789437b/config.default.yaml#L66-L67
> > 
> > Regarding the issue you reported, it's clearly a bug. I suspect, it is caused by a way in which are defined electrical parameters of the new DC lines introduced during augmentation. Thanks to reporting it and happy to receive fixes for that.
> 
> Pakistan network is well interconnected so, I agree with you that there is no need for augmentation in Pakistan's case.

**Comment by Abdul-Karim786** [comment]
> > > > Yes, the above network is the result of augmentation. I am exploring the pypsa-earth in every aspect of Pakistan's modeling that's why I am going with different settings to understand pypsa-earth very well.
> > > 
> > > 
> > > Thank you for the clarification. To my understanding, augmentation may not be needed to build a power model for Pakistan, as national system seems still to be well interconnected.
> > > If there are any imperfect data in the network topology, that can be corrected using options to drop isolated nodes (if any), or merge them into the network. If isolated networks present in the system, it is possible to merge them into a backbone network. The following config parameters can be used to control this functionality:
> > > https://github.com/pypsa-meets-earth/pypsa-earth/blob/e3aefd4ae065fa31244ed20ec23ad6129789437b/config.default.yaml#L66-L67
> > > 
> > > Regarding the issue you reported, it's clearly a bug. I suspect, it is caused by a way in which are defined electrical parameters of the new DC lines introduced during augmentation. Thanks to reporting it and happy to receive fixes for that.
> > 
> > 
> > Pakistan network is well interconnected so, I agree with you that there is no need for augmentation in Pakistan's case.
> 
> > > > Yes, the above network is the result of augmentation. I am exploring the pypsa-earth in every aspect of Pakistan's modeling that's why I am going with different settings to understand pypsa-earth very well.
> > > 
> > > 
> > > Thank you for the clarification. To my understanding, augmentation may not be needed to build a power model for Pakistan, as national system seems still to be well interconnected.
> > > If there are any imperfect data in the network topology, that can be corrected using options to drop isolated nodes (if any), or merge them into the network. If isolated networks present in the system, it is possible to merge them into a backbone network. The following config parameters can be used to control this functionality:
> > > https://github.com/pypsa-meets-earth/pypsa-earth/blob/e3aefd4ae065fa31244ed20ec23ad6129789437b/config.default.yaml#L66-L67
> > > 
> > > Regarding the issue you reported, it's clearly a bug. I suspect, it is caused by a way in which are defined electrical parameters of the new DC lines introduced during augmentation. Thanks to reporting it and happy to receive fixes for that.
> > 
> > 
> > Pakistan network is well interconnected so, I agree with you that there is no need for augmentation in Pakistan's case.

Thank you for sharing, I will check these parameters of the DC line when there is a need of augmentation to avoid from bug
