### ISSUE TITLE
remove snakemake dependecies from functions

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#106]
Functions should also work also outside the snakemake workflow. (See PyPSA-Eur PR here https://github.com/PyPSA/pypsa-eur/pull/275). Instead of using snakemake in a function, we should simply assign it to a variable.

An example of do's and don'ts
**Don't:**
`def load(n, cost=snakemake.input["cost"]):`

**Don't:**
>`def load(n):`
>>cost=snakemake.input["cost"]

**Do:**
>`def load(n, costs):`
>> cost=costs

and later at the execution important the i.e. costs from snakemake:
costs = snakemake.input["cost"]

**Comment by pz-max** [comment]
@Hazem-IEG, @davide-f  We already partially applied the do's. At some point we should clean up function by function.

**Comment by davide-f** [comment]
The only major function where it is heavily used is base_network; I've cleaned in other functions in a PR #580

**Comment by davide-f** [comment]
Revision: they are all revised; I think we can close this issue once the PR is merged
