### ISSUE TITLE
build_renewable_profiles - offwind/hydro bugs

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#108]
A couple of functions are commented in the `build_renewable_profiles` script.
We should activate them and test their functionality.

**Comment by pz-max** [comment]
@Ay-Khi

**Comment by davide-f** [comment]
I'm investigating it unless @Ay-Khi is actually working on it

**Comment by davide-f** [comment]
I may bring updates soon.
Regarding the land cover classification, we may need to change the corine one that was used by PyPSA-EUR as it applies only for Europe.
We could use the UN-FAO classification (http://www.fao.org/3/x0596e/X0596e01i.htm#P1473_136884); a open source dataset for the globe is available at: https://zenodo.org/record/3939050#.YV9po9pBxPY
With respect to Coring, which had 44 classes, the new one has 32 classes. It may be acceptable. I'll be implementing it in the meantime

**Comment by davide-f** [comment]
With 450b06969a5493e8067f3ed57d4022c1eb0718ba, dd2084fd51dfadbf5fde851874b5677e27e3b1a0 and f893b263efa4726c916f7dd2b0ef8919b0414f56 a draft version of build_renewable_profiles with hydro and basically everything uncommented.
Things left to do:
- [ ] crosschecking the inflow drawn by the methodology with a practical example
- [ ] calculate hydro inflows only for buses where hydro technology is implemented (to save computational time)

Notes:
- To implement a corine-like approach, insted of using the corine dataset, which applies only for europe, I chose the Copernicus global service (https://land.copernicus.eu/global/). Note that the corine dataset is still Copernicus, but with a different nomenclature, see previous comment
- I updated the gebco dataset with the global one

**Comment by pz-max** [comment]
@davide-f this can be closed?

**Comment by davide-f** [comment]
> @davide-f this can be closed?

Unfortunately no.

I've been investigating this issue, and for three hydro powerplants in Nigeria, even using the 8th or 12th hydrobasin level, only 1 plant gets a time series.
This feels very weird.


After having deeply investigated atlite and its procedure, the reason why we are experiencing that null value is because nan values are returned for such stations
![image](https://user-images.githubusercontent.com/67809479/172030863-f697c2cf-eb7d-4a8e-990f-5c9c2543290a.png)

I'll look forward to understand the issue

**Comment by davide-f** [comment]
I think I've found a atlite-related major issue that was leading to the above problem.
The issue has been opened including a PR on atlite (https://github.com/PyPSA/atlite/pull/242)
