### ISSUE TITLE
Run-of-River hydro power plants ignored when using a custom_powerplants.csv-based powerplants.csv

### ISSUE THREAD

**Issue by danielelerede-oet** [pz-max/pypsa-africa#1081]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

*This issue has been experienced when adopting a custom_powerplants.csv file to build powerplants.csv: all hydro power plants of technology type "Run-of-River" (or, equivalently, having no "technology" assigned, as the "Run-of-River" class is then given by default as from add_electricity.py) are ignored and neither any capacity nor electricity generation from them is taken into account.*

**Comment by ekatef** [comment]
Thanks a lot for sharing that @danielelerede-oet! The issue has not been reported before but sounds like potentially quite a serious one

**Comment by ekatef** [comment]
Hey @danielelerede-oet, thanks for working on that. Just to be sure, the reason you identified have been formatting issues in `custom_powerplants.csv` file, correct?

**Comment by Abdul-Karim786** [comment]
> ## Checklist
> * [x]  I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
> * [x]  I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.
> 
> ## Describe the Bug
> _This issue has been experienced when adopting a custom_powerplants.csv file to build powerplants.csv: all hydro power plants of technology type "Run-of-River" (or, equivalently, having no "technology" assigned, as the "Run-of-River" class is then given by default as from add_electricity.py) are ignored and neither any capacity nor electricity generation from them is taken into account._

Hey @danielelerede-oet, the issue is with the formatting of custom_powerplants.csv. Write Run-Of-River in the technology column instead of Run-of-River.

**Comment by danielelerede-oet** [comment]
Yes @ekatef . Indeed it wasn't a problem related with the script. In any case, it would be beneficial to add some checks in the `build_powerplants.py` script to avoid a wide range of undetectable errors (i.e., capital letters, mistakes in the definition of FuelType or Technology) one can make when compiling a `custom_powerplants.csv`.
