### ISSUE TITLE
Check gdrive link

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#1091]
## Checklist

- [ ] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [ ] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

*Please provide a description of what the bug is and add a minimal example/command for reproducing the bug.*

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```bash
<paste here>
```

**Comment by ekatef** [comment]
Hey @davide-f, may it be a good idea to add a short description of the issue? We could have discussed it but I'm not quite sure I remember the details

**Comment by ekatef** [comment]
Hello @davide-f, could you please check the status of this issue? We have now cutouts for all macro-regions of the world, may it have resolved this issue?
