### ISSUE TITLE
Importing PyPSA-Earth rules and using is troublesome

### ISSUE THREAD

**Issue by yerbol-akhmetov** [pz-max/pypsa-africa#1115]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

Relative paths in PyPSA-Earth seem to cause issue when `pypsa-earth` rules are imported using module into other snakemake. In short, I was preparing a snakemake workflow for the project including `pypsa-earth` rules using module functionality of snakemake:
```bash
module pypsa_earth:
    snakefile:
        "submodules/pypsa-earth/Snakefile"
    config:
        config

use rule * from pypsa_earth
```

After importing pypsa-earth rules into another snakemake workflow, then running any command like `retrieve_databundle_light` or `clean_osm_data` causes MissingInputException because it cannot find inputs for rules that  
 have inputs. While for retrieve related rules, it stores output files into drives root directory (e.g. C://). Appending `pypsa-earth` directory as path  into external Snakefile does not help to resolve the issue. I have indicated the error message screen. 

The issue seems to resolve when we use absolute path to input/outputs of snakemake and for some functions in `_helpers.py` script. The example is shown below too. If someone would like to try it out, this [PR](https://github.com/user-attachments/assets/ccb85ba8-3d19-4c52-b46a-3927fccb5acc) can be looked at.

## Error Message

![image](https://github.com/user-attachments/assets/37100c6d-18e9-48da-b996-e753bf2d3237)
## Possible solution:
![image](https://github.com/user-attachments/assets/cd911be9-97fe-4adf-a71f-06e0d6d496df)
where BASE_DIR is defined in `_helpers.py` script as:
![image](https://github.com/user-attachments/assets/663c9128-13fc-4d93-8827-70baeeadc452)

**Comment by davide-f** [comment]
Closing as solved by #1137 , many thanks for the contribution! :)
