### ISSUE TITLE
Failed to retrieve resource for Emission Extractor

### ISSUE THREAD

**Issue by GbotemiB** [pz-max/pypsa-africa#1140]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

*Please provide a description of what the bug is and add a minimal example/command for reproducing the bug.*
The workflow is falling to download resource needed for emission_extractor as the site is currently under maintenance. Here is the link https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/v60_GHG/CO2_excl_short-cycle_org_C/v60_GHG_CO2_excl_short-cycle_org_C_1970_2018.zip

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```bash
Failed download resource from 'https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/v60_GHG/CO2_excl_short-cycle_org_C/v60_GHG_CO2_excl_short-cycle_org_C_1970_2018.zip'.
ERROR:__main__:Failed download resource from 'https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/v60_GHG/CO2_excl_short-cycle_org_C/v60_GHG_CO2_excl_short-cycle_org_C_1970_2018.zip'.
ERROR:_helpers:An error happened in module '/Users/gbotemi/miniconda3/envs/pypsa-earth/lib/python3.10/genericpath.py', function '_check_arg_types': join() argument must be str, bytes, or os.PathLike object, not 'bool'
Traceback (most recent call last):
  File "/Users/gbotemi/Documents/code/PYPSA/docker/pypsa-earth/.snakemake/scripts/tmpso8kaj2n.prepare_network.py", line 369, in <module>
    co2limit = emission_extractor(
  File "/Users/gbotemi/Documents/code/PYPSA/docker/pypsa-earth/.snakemake/scripts/tmpso8kaj2n.prepare_network.py", line 124, in emission_extractor
    datapath = os.path.join(os.getcwd(), "data", filename)
  File "/Users/gbotemi/miniconda3/envs/pypsa-earth/lib/python3.10/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/Users/gbotemi/miniconda3/envs/pypsa-earth/lib/python3.10/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'bool'
```
<img width="1214" alt="image" src="https://github.com/user-attachments/assets/30cf4cf4-3b00-4222-9fe6-7422433cae66">

**Comment by davide-f** [comment]
Hello @GbotemiB :)
Can we close this? It seems the service is back online

**Comment by GbotemiB** [comment]
Sure, we can. Thank you very much.
