### ISSUE TITLE
Duplicate entries in `data/AL_production.csv` data in `build_industry_format`

### ISSUE THREAD

**Issue by yerbol-akhmetov** [pz-max/pypsa-africa#1142]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

Good day. There is an error happening while executing `build_industry_format` rule for US (probably other countries too) related to duplicate entries in `data/AL_production.csv` file. There are two entries for 2019 for US: 1) 1100 ktons/a from Wikipedia and 2) 0 with comment (no available information online assumed value of 0). Best solution would be fixing it at source. However, I propose to accommodate the code to handle such situations.

## Error Message

![image](https://github.com/user-attachments/assets/112a72cb-2e77-4782-b59b-e8955b27d918)

**Comment by davide-f** [comment]
Closing as PR is merged :)
