### ISSUE TITLE
H2 re-addition in sector causes error

### ISSUE THREAD

**Issue by yerbol-akhmetov** [pz-max/pypsa-africa#1144]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

Good day, I have faced the issue when simulation sector-coupled network for US. The error occurs in `prepare_sector_network` and is related to re-addition of H2 carrier. Since it can already exist in power version, it throws an error. Please see the message. This is potentially a huge issue as H2 Stores are already in the network, while `prepare_sector_network` tries to add `H2 UHS Store`. I do not know if it is intended to keep all power H2 Stores and carrier. I will try to create a draft PR on that. The same is true for `battery` too.

## Error Message

![image](https://github.com/user-attachments/assets/66532b34-c0a2-4ff3-88da-6f987df13a4a)

**Comment by GbotemiB** [comment]
Hi @yerbol-akhmetov, I have faced this recently. My workaround is to simply remove the stores `h2` and `battery`. Then rerun the workflow.

**Comment by hazemakhalek** [comment]
@yerbol-akhmetov: I agree with @GbotemiB, this is the way to go. 
The way we used the sector-coupled model before is by making sure we don't carry over H2 and battery from pypsa-earth.

If you want to implement it differently in the config file, I'm happy to review!

**Comment by yerbol-akhmetov** [comment]
Thanks, @hazemakhalek. I am actually not quite sure what approach is better. I have created a draft PR. My workaround was just adhoc to make sure to carrier (H2 and battery) is not added if it is present. I would like to know if it ok to have both H2 Store and H2 UHS Store. Or dropping mechanism needs to be implemented.

**Comment by yerbol-akhmetov** [comment]
> Hi @yerbol-akhmetov, I have faced this recently. My workaround is to simply remove the stores `h2` and `battery`. Then rerun the workflow.

Thanks, @GbotemiB. I just added if statement to not add carrier if it is present. I am not quite sure, what would be best approach. And it needs to be upstream definitely.

**Comment by hazemakhalek** [comment]
> Thanks, @hazemakhalek. I am actually not quite sure what approach is better. I have created a draft PR. My workaround was just adhoc to make sure to carrier (H2 and battery) is not added if it is present. I would like to know if it ok to have both H2 Store and H2 UHS Store. Or dropping mechanism needs to be implemented.

In principle it's okay to have H2 storage (tanks) as well as UHS. 
On a side note: we have redundant parameters in the config files for underground hydrogen storage (UHS). Maybe we need to clean that out since we're already at it.

What you implemented in principle is okay, and is more or less already tested. A cleaner way, however, is to check first if H2 is already there before trying to add it again in prepare_sector_network. I can't quickly decide if there are other considerations we need to keep in mind for this approach, I'm now mainly signaling the better approach in my opinion but it needs to be tested.
