### ISSUE TITLE
Mismatch between length of bus0 and bus1 while adding SMR and other technologies in `prepare_sector_network.py` 

### ISSUE THREAD

**Issue by yerbol-akhmetov** [pz-max/pypsa-africa#1148]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

Good day. The issue is related to addition of SMR into the network in `prepare_sector_network.py` script in `h2_hc_conversions` function. When adding SMR of SMR CC, the error of mismatch between bus1 and bus0. In particular, `nodes` are used for bus1 and `spatial.gas.nodes` are used for bus0. It causes error, as `nodes` consider only AC nodes, while `spatial.gas.nodes` considers both AC and DC nodes. So error is related to this piece of code:
```bash
            n.madd(
                "Link",
                spatial.nodes,
                suffix=" SMR CC",
                bus0=spatial.gas.nodes,
                bus1=nodes + " H2",
                bus2="co2 atmosphere",
                bus3=spatial.co2.nodes,
                p_nom_extendable=True,
                carrier="SMR CC",
                efficiency=costs.at["SMR CC", "efficiency"],
                efficiency2=costs.at["gas", "CO2 intensity"]
                * (1 - options["cc_fraction"]),
                efficiency3=costs.at["gas", "CO2 intensity"] * options["cc_fraction"],
                capital_cost=costs.at["SMR CC", "fixed"],
                lifetime=costs.at["SMR CC", "lifetime"],
            )
```

## Error Message

![image](https://github.com/user-attachments/assets/52efb8fe-763f-4c0a-baa5-7176c8c6c8c0)

The fix will be presented in this [PR](https://github.com/pypsa-meets-earth/pypsa-earth/pull/1145)
@hazemakhalek

**Comment by hazemakhalek** [comment]
Thanks for pointing this out. So far we only worked with force_AC turned on.
A good permanent solution here will be great. It has to accommodate for the Force_AC case as well
@yerbol-akhmetov

**Comment by yerbol-akhmetov** [comment]
@davide-f , I am closing the issue as it was solved by merged PR https://github.com/pypsa-meets-earth/pypsa-earth/pull/1145/files
