### ISSUE TITLE
Allow pre-commit and documenter to run less frequently

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#1176]
## Describe the feature you'd like to see

Reduce the frequency of pre-commit and documenter automatic actions

**Comment by ekatef** [comment]
@davide-f Completely agree 😄 Hasn't #1210 fixed it? Do we have any other points to address here?

**Comment by davide-f** [comment]
We can close for now, it could be run even less frequently probably XD ok for now

**Comment by davide-f** [comment]
Update: by using github.repository property in the github action, we could ensure the documenter to be triggered only on upstream, which is desirable
