### ISSUE TITLE
Detect energy access

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#120]
An Open Source method to estimate areas without electricity access. Maybe worth adding it, we could create minigrids/ or future grid expansion based on the results: https://www.nature.com/articles/s41597-019-0347-4

![image](https://user-images.githubusercontent.com/61968949/138462884-37278a97-c944-4a56-9082-bec70a149dbe.png)

**Comment by pz-max** [comment]
@Nayara2020 can recommend that paper. The described energy access quantification might be also interesting for you

**Comment by davide-f** [comment]
I think we can close this PR
