### ISSUE TITLE
error in rule build_natura_raster

### ISSUE THREAD

**Issue by mirjam-ji** [pz-max/pypsa-africa#1214]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

I do receive an error in rule build_natura_raster. I think the problem is in th inputs from data/landcover but I don't know how to fix it. ## Describe the Bug

*Please provide a description of what the bug is and add a minimal example/command for reproducing the bug.*

## Error Message

[Thu Nov 28 13:17:50 2024]
rule build_natura_raster:
    input: data/landcover, cutouts/cutout-2013-era5.nc, cutouts/cutout-2013-era5.nc, cutouts/cutout-2013-era5.nc, cutouts/cutout-2013-era5.nc, cutouts/cutout-2013-era5.nc, cutouts/cutout-2013-era5.nc
    output: resources/PL_2050_with_nuclear/natura.tiff
    log: logs/PL_2050_with_nuclear/build_natura_raster.log
    jobid: 8
    benchmark: benchmarks/PL_2050_with_nuclear/build_natura_raster
    reason: Missing output files: resources/PL_2050_with_nuclear/natura.tiff; Input files updated by another job: cutouts/cutout-2013-era5.nc
    resources: tmpdir=/tmp

/home/mirjam-ji/anaconda3/envs/pypsa-earth/lib/python3.10/site-packages/pypsa/networkclustering.py:16: UserWarning: The namespace `pypsa.networkclustering` is deprecated and will be removed in PyPSA v0.24. Please use `pypsa.clustering.spatial instead`. 
  warnings.warn(
Stage 1/5: Determine cutout boundaries
INFO:__main__:Stage 1/5: Determine cutout boundaries
Stage 1/5: Determine cutout boundaries
INFO:__main__:Stage 1/5: Determine cutout boundaries
Stage 1/5: Determine cutout boundaries
INFO:__main__:Stage 1/5: Determine cutout boundaries
Stage 1/5: Determine cutout boundaries
INFO:__main__:Stage 1/5: Determine cutout boundaries
Stage 1/5: Determine cutout boundaries
INFO:__main__:Stage 1/5: Determine cutout boundaries
Stage 1/5: Determine cutout boundaries
INFO:__main__:Stage 1/5: Determine cutout boundaries
Stage 2/5: Get transform and shape
INFO:__main__:Stage 2/5: Get transform and shape
Stage 3/5: Unify protected shape area.
INFO:__main__:Stage 3/5: Unify protected shape area.
Stage 3/5: Unify protected shape area. Step 1: Create one geodataframe with all shapes
INFO:__main__:Stage 3/5: Unify protected shape area. Step 1: Create one geodataframe with all shapes
[Thu Nov 28 13:25:16 2024]
Error in rule build_natura_raster:
    jobid: 8
    input: data/landcover, cutouts/cutout-2013-era5.nc, cutouts/cutout-2013-era5.nc, cutouts/cutout-2013-era5.nc, cutouts/cutout-2013-era5.nc, cutouts/cutout-2013-era5.nc, cutouts/cutout-2013-era5.nc
    output: resources/PL_2050_with_nuclear/natura.tiff
    log: logs/PL_2050_with_nuclear/build_natura_raster.log (check log file(s) for error details)

RuleException:
CalledProcessError in file /mnt/c/Users/mirja/OneDrive/Dokumente/pypsa-earth/Snakefile, line 375:
Command 'set -euo pipefail;  /home/mirjam-ji/anaconda3/envs/pypsa-earth/bin/python3.10 /mnt/c/Users/mirja/OneDrive/Dokumente/Studium/Semester7/Projektarbeit/Repositories/pypsa-earth/.snakemake/scripts/tmpntwbitiy.build_natura_raster.py' died with <Signals.SIGKILL: 9>.
  File "/mnt/c/Users/mirja/OneDrive/Dokumente/pypsa-earth/Snakefile", line 375, in __rule_build_natura_raster
  File "/home/mirjam-ji/anaconda3/envs/pypsa-earth/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```bash
<paste here>
```

**Comment by ekatef** [comment]
Hello @mirjam-ji, a likely reason is lack of RAM: there is an indication on `Signals.SIGKILL: 9` in the traceback you shared

Note please that a pre-compiled `natura.tiff` raster exists. To get a feeling on how all the pieces work together, I'd recommend to go trough the `Short Tutorial`, and `Model Customisation` in the documentation.

**Comment by LRydin** [comment]
I can confirm that this is the case. I am building my own natural raster (11 countries in southern Africa) and it takes about 60GB of RAM. Note that building the raster is a rather long process (or something is wrong with my machine), as it has been running on a single core for 18 hours now.

**Comment by ekatef** [comment]
> I can confirm that this is the case. I am building my own natural raster (11 countries in southern Africa) and it takes about 60GB of RAM. Note that building the raster is a rather long process (or something is wrong with my machine), as it has been running on a single core for 18 hours now.

@LRydin thanks for letting know! To load this dataset, you need to use `build_natura_raster: false`. Do you have any specific reasons to build a custom `natura.tiff` for your problem?

As a comment, the global `natura.tiff` raster is supplied with the model. It should be loaded using these urls

https://github.com/pypsa-meets-earth/pypsa-earth/blob/7185b74e29ec75f848ac4c4e3e6bca96963a7f67/configs/bundle_config.yaml#L187-L196

**Comment by LRydin** [comment]
@ekatef, I followed the procedure and downloaded the raster instead of creating it, just like you suggested :). It worked perfectly, thanks!

From my view, if @mirjam-ji and you @ekatef agree, this issue could be closed :).

**Comment by mirjam-ji** [comment]
Thank you! Yes I agree, the issue could be closed.

**Comment by davide-f** [comment]
Thanks for notifying, closing :)
