### ISSUE TITLE
H2 export loads are not satisfied due to duplicate `hydrogen_buses_ports`

### ISSUE THREAD

**Issue by yerbol-akhmetov** [pz-max/pypsa-africa#1231]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

Good day, I have noticed a bug that leads an infeasibility of sector network. The issue was noticed when simulating US. It is related to `H2 export`, where H2 load is added in `add_export.py` script. However, the links that will connect external `H2 export bus` containing H2 load and internal H2 buses are not added. It is because the names are duplicate for `hydrogen_buses_ports` used to define links, as a result, the links are not added (which cause infeasibility as demand is not satisfied). I have found the cause of the issue by making `load_shedding: true`. So probably we need to remove duplicates to solve the issue. @ekatef @davide-f 

![image](https://github.com/user-attachments/assets/262bb286-cb9e-49ed-a345-531c973f2911)

![image](https://github.com/user-attachments/assets/9383114f-e6ab-4888-9957-749c56fdb332)

## Error Message

![image](https://github.com/user-attachments/assets/13dcc9d3-1cf3-4e93-9e9c-e445b5e4c76d)

Having links `repurposed` without buses connected is another topic that I will study.

**Comment by ekatef** [comment]
Hello @yerbol-akhmetov, thanks for the reporting and working on the fix! Has the issue been resolved with #1233?

**Comment by yerbol-akhmetov** [comment]
Thanks, @ekatef, for pointing that out. Yes, the issue was resolved with that PR. I will close the issue.

**Comment by ekatef** [comment]
> Thanks, @ekatef, for pointing that out. Yes, the issue was resolved with that PR. I will close the issue.

Many thanks for fixing that! 😄
