### ISSUE TITLE
Lines "overpassing" nodes

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#124]
While debugging and crosschecking the code regarding #121 , I noticed that the geometry describing a line may be overpassing some substations the line most likely is connected to.
To better clarify the above, let's see the image below, taken from a substation in Nigeria; the axes represent the longitude/latitude of the output of the osm_data_cleaning script for reproducibility. The script used to produce the images is "simplify_and_cluster_network" in #121 

**Image A**
![image](https://user-images.githubusercontent.com/67809479/139098447-eccdd8c7-3bed-458d-b346-4762aa867848.png)

**Image B: Zoomed area**
![image](https://user-images.githubusercontent.com/67809479/139098032-cf0a6a47-8651-4545-972e-3babbaab8c07.png)

By looking at image A, I expect the yellow bus in the middle to be electrically connected to the other line in blue. However, this is not the case.
As a result, the simplify network script gathers the two nodes and collapse them into a single bus not being interconnected to the rest of the network.
In fact you can see the yellow dot not being connected to the line.
![image](https://user-images.githubusercontent.com/67809479/139098877-8c68a7b9-eeab-451b-aa2b-953a75850da1.png)

This problem must be tackled as it can lead to dramatically change the network topology of a country, because two lines ending in two neighboring substations, but different, may not be recognised as connected.
As a temporary fix, I used a relatively large tolerance of the tolerance used for grouping the substations.

To solve that issue, in the osm_data_cleaning process, there is the need to crosscheck whether the geometry path of the line is within a tolerance from any other substation, except the endings. When that occurs, the geometry of the line shall be split in several branches to avoid that issue.
The function split from shapely.ops can be the way to go

**Comment by pz-max** [comment]
Good spot! Indeed something we could correct by the method you mentioned
