### ISSUE TITLE
Main documentation page: book an appointment, zoom link for code&data

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#126]
Not sure if it's my case, but the link to book an appointment seems not working in my case.
It may be verified
https://github.com/pypsa-meets-africa/pypsa-africa/blob/new-main/app.autobook.me/max-parzen/pypsa-meets-africa

Moreover, we better define the "static" link to a zoom call for the Code&Data meetings as discussed

**Comment by davide-f** [comment]
#a1f3347d1098a148abcb781abdd361aa0725deb0 and the index in github.
A page on the documentation is needed to describe the meetings and then this issue can be closed

**Comment by pz-max** [comment]
Hi Davide, 
Your above link does not work.
However, the link in the ReadMe works ! :)

**Comment by pz-max** [comment]
Regarding the Zoom call, is it recurring at the moment?
Should we change it and the .ics need then the new link?

**Comment by davide-f** [comment]
The ics should be recurrent, I checked it on my pc.
If you crosscheck it, we can confirm the validity.
Unless we need to change the zoom link, the current file is fine.
We may improve the description in the ics but they are pure details.

To clarify, I created the file with Microsoft outlook, it is pretty
straightforward there, but I'm sure there are also many other software to
do so.

**Comment by pz-max** [comment]
https://github.com/pypsa-meets-africa/pypsa-africa/commit/b6f911e87aa48bb84e379d6c86bf74940e0f9385
closes #126
