### ISSUE TITLE
Check and fix jupyter notebooks

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#128]
Will work on Saturday on that. This will help the newbies to explore and use some of the stuff.

Early next week, I will work then on fixing the solver_network run to hopefully approve that everything solves well!

**Comment by pz-max** [comment]
Some Jupyter notebooks are checked now with commit https://github.com/pypsa-meets-africa/pypsa-africa/commit/81978bc439b078d5a2fde7ec4eaa0076baf481a4 . 

- [ ] Some remaining notebooks that need some work are marked with zero at the beginning such as `0_network_comparison.ipynb`

**Comment by davide-f** [comment]
Outdated issue
