### ISSUE TITLE
Verify appropriate data cleaning of None geometries and NAN data

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#131]
Along the Dataworkflow, it occurs that None geometries in the data inputs are removed along the process.
The scripts should be revised so that the cleaning phase is performed the earlier the possible, which means that in the scripts base_network and cluster_network there is no need for filtering out None shapes
The points in the code where this elements occur are highlighted by TODOs:
**cluster_network**
https://github.com/pypsa-meets-africa/pypsa-africa/blob/349fbdff410edcd191ce48fb44d2a2fcfa03363d/scripts/cluster_network.py#L396
**base_network**
https://github.com/pypsa-meets-africa/pypsa-africa/blob/349fbdff410edcd191ce48fb44d2a2fcfa03363d/scripts/base_network.py#L141

In particular, the cleaning of None geometries of the base_network shall be performed in osm_data_cleaning instead and verify that osm_built_network works without generating issues.
The cleaning of None shapes occurring in cluster_network, which is related to the shapes "regions_onshore" and "regions_offshore" created in the build_bus_regions,  should be moved in build_shapes and build_bus_regions.

Moreover, it would be nice to map whereelse NAN and None data are removed also in other scripts and check if that can be pushed upstream in the code.

**Comment by davide-f** [comment]
I believe this issue is now outdated. Closing as no more relevant

**Comment by pz-max** [comment]
The onshore/offshore Nan shape stuff is not dealt perfectly. However ableget issue is open describing how to do this much better. I am just waiting for the right person to do this (for training purposes)

**Comment by davide-f** [comment]
I think we can close this PR, we have fixed and are fixing problems when they come
