### ISSUE TITLE
Verify current Data workflow for Turkey

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#133]
The current data workflow should be tested for non-African countries, starting from Turkey for example.

This means that in the config file, the user should change the parameter "country" into "TR" to run the current software for Turkey and report all the problems along the analysis.
To verify the execution, the user should verify if any error occurs and the quality of the results using the notebooks available in the notebooks folder

**Comment by davide-f** [comment]
@oayana, @EmreYorat, or someone else you know,  may someone of you like to be in charge of this issue?
If so, just write and I assign you to this issue

**Comment by oayana** [comment]
> @oayana, @EmreYorat, or someone else you know, may someone of you like to be in charge of this issue? If so, just write and I assign you to this issue

Hi @davide-f :)

I and @EmreYorat came to the last stage for Turkey, namely the solve_all_networks script. All other scripts are running. Now we are trying to choose a solver and run the last step.

At this stage, if you wish, We can perform the validation process. Do you have a list of things to do for this, or should we just run the notebooks for Turkey and check the outputs?

**Comment by davide-f** [comment]
Awesome! Good job!
So, I'd say that this issue can be closed.

As a recommendation, you can try to use glpk or highs solver (see documentation).
Regarding the glpk solver, it is already in the environment and if you open the config.tutorial.yaml you should see the example about how to use it.
Anyway, since you are students, you can apply for a free educational license of gurobi as well.

Regarding the validation, I recommend to follow the recommendation stated in #224 . Basically, you can use the sample validation notebook for Nigeria in notebooks/validation/validation_nigeria.ipynb as a template for the Turkish case.
The validation implies to crosscheck the data that the workflow obtains with third party data (e.g. data from tso or national/sovranational institutions, the more the better :))

**Comment by oayana** [comment]
> Awesome! Good job! So, I'd say that this issue can be closed.
> 
> As a recommendation, you can try to use glpk or highs solver (see documentation). Regarding the glpk solver, it is already in the environment and if you open the config.tutorial.yaml you should see the example about how to use it. Anyway, since you are students, you can apply for a free educational license of gurobi as well.
> 
> Regarding the validation, I recommend to follow the recommendation stated in #224 . Basically, you can use the sample validation notebook for Nigeria in notebooks/validation/validation_nigeria.ipynb as a template for the Turkish case. The validation implies to crosscheck the data that the workflow obtains with third party data (e.g. data from tso or national/sovranational institutions, the more the better :))

Hi @davide-f ,

Thanks for the your suggestions, I'll try both solvers. Solving is taking a long time, i think I need to find a suitable time for it :)

I hope to complete the validation process as soon as possible and share it :)

**Comment by davide-f** [comment]
For testing purposes and faster time speed you can use lower number of clusters, which can be set in the wildcards of the config file. How many clusters are you using?

**Comment by oayana** [comment]
Here, i think the default number of clusters is 6. But I can choose a smaller number if you think it will be faster?

**Comment by davide-f** [comment]
6 clusters should be fine, does it take so long to solve?

**Comment by oayana** [comment]
I haven't done a full run for solving yet. I just said it takes a long time as I watched from pypsa-eur videos :)

**Comment by davide-f** [comment]
In the PR #260 I tested also turkey with the workflow and it worked fine :)
Do not be shared of using glp, in case you can simplify the approach and reducd the size of the problem.
I think 6 clusters should be fine to solve at least in testing phase.
