### ISSUE TITLE
Fix environments - hv.plot and geoplot

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#137]
- [ ]  0_network_comparison.ipynb, and other scripts use `hvplot()` which usually generated an interactive map where one can zoom and see components in detail. However, the plot is not showing which might be related to bookeh or something else. This probably requires an environment fix (previous "toast" environment created the right output)

- [ ] 0_osm_powermap.ipynb requires the `geoplot` package. One need to proceed in the following order to add `geoplot`:
- deinstall the the pypsa-africa environment,
- the pypsa-africa kernel for the jupyter notebook, 
- install geoplot
- install pypsa-africa on the jupyter kernel
- test all the notebooks if geoplot leads to issues

**Comment by davide-f** [comment]
Regarding hvplot, on my computer it works with the new environment.
Yet, I suggest to clean the results and reprocess the images with the new environment.
The results obtained with previous versions may not get well recognized maybe; when I rerun the script I had no problems.
