### ISSUE TITLE
Set world dictionary in osm_data_config only for osm and create a new one for managing regions

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#182]

**Comment by ekatef** [comment]
@davide-f Thank you for creating the issue!

The `world` dictionary structure in the osm_data_config.py currently corresponds to ISO, right?
If I understand it properly, I could continue checking how does`world` dictionary  corresponds to the Geofabrik data structure and create an additional  `geofk_word` intended for data access.

**Comment by pz-max** [comment]
> @davide-f Thank you for creating the issue!
> 
> The `world` dictionary structure in the osm_data_config.py currently corresponds to ISO, right? If I understand it properly, I could continue checking how does`world` dictionary corresponds to the Geofabrik data structure and create an additional `geofk_word` intended for data access.

Yep you are right @ekatef :) The `geofk_world` would be highly appreciated

**Comment by ekatef** [comment]
Great, thank you!

**Comment by davide-f** [comment]
#236 solves this issue. Some refinings and checks are still needed.
Once @ekatef has finished the checks, this issue can be closed

**Comment by davide-f** [comment]
Closed as #249 has been merged
