### ISSUE TITLE
Upload release code and pre-build network to Zenodo

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#206]
As done for PyPSA-Eur:

- [ ] Upload code to zenodo code repository similar as [PyPSA-Eur](https://zenodo.org/record/5521701#.YcXLd9so-EA)

- [ ] Create pre-built networks for ``config.default.yaml`` by running ``snakemake -j 1 extra_components_all_networks``.

- [ ] Upload pre-built networks to zenodo data repository as [PyPSA-eur](https://doi.org/10.5281/zenodo.3601881) with [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) license.

- [x] #241

**Comment by davide-f** [comment]
I think we can close this issue
