### ISSUE TITLE
Data validation

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#224]
### The issue

With the recent developments, the model successfully works for the entire Africa continent, however, the data of the workflow shall be validated with established and valid data available from third parties, such as [IEA](https://www.iea.org/), [IRENA](https://www.irena.org/) or alike. Best would be to validate and compare the data by many sources.

This issue aims to keep track of the updates. 

We always welcome contributions. Pick (your) country and validate it, max 1 day needed per country using our templates!

### How to contribute

Please, join us, choose your country and validate the data.
In practise:
1. Fork our repository and feel confident with it. Our [hackaton material](https://github.com/pypsa-meets-africa/pypsa-africa-hackathon) may be in handy to learn.
2. Post to reserve your country
3. Create a local branch of our main repository in your local computer and develop your validation notebook using the template for Nigeria available in the folder `notebooks/validation/validation_nigeria.ipynb`, best comparing multiple sources of data, such as [IEA](https://www.iea.org/), [IRENA](https://www.irena.org/); feel free to add more sources.
4. Create a pull request in github to push your commit to the main branch and refer this issue in the description to track the updates

Once completed and the pull request is merged, the following table will be updated to include the proposed validation

### Updated validation table (updated)

The following table contains the updated list of validated countries (alphabetic order).

| Country |                 IEA                |             IRENA              |       National sources     |    Validator username  |
|----------|--------------------------|--------------------------|--------------------------|--------------------------|
| Nigeria |    :heavy_check_mark:    |                                     |     :heavy_check_mark: ([Nigerian TSO](https://www.tcn.org.ng/))  |            @davide-f         |

**Comment by davide-f** [comment]
To validate South-Africa, PyPSA-ZA is very handy! https://github.com/PyPSA/pypsa-za

**Comment by ekatef** [comment]
FYI @Ekaterina-Vo

**Comment by ekatef** [comment]
I would also add the World Bank database https://energydata.info/dataset

@Ekaterina-Vo could you please put there any data sources for Central Asia?

**Comment by ekatef** [comment]
Comprehensive data on hydropower and reservoirs in Central Asia are available via http://www.cawater-info.net/bk/water_land_resources_use/register/index.html (courtesy of [the Central Asia Water project](https://www.cawa-project.net/))

There are also data by countries and basins in the region which can be important to establish a proper context for validation http://www.cawater-info.net/bd/

Excellent data on the power supply and demand can be found via national open data services. For Central Asia:
https://www.korem.kz/ (reports are currently available in Kazakh and Russian)
https://data.egov.uz/ (e.g. power generation data https://data.egov.uz/eng/data/6138961c14665dbb8ec78b74)
http://www.stat.kg/ (in particular, consumption of electricity, heat and water http://www.stat.kg/ru/opendata/category/3557/)

FYI @Ekaterina_Vo

**Comment by ekatef** [comment]
Generalising a bit work done for Nigeria, Africa and Central Asia countries, the following validation points (supported by Jupiter Notebooks) are worth attention:

1. Check the [power grid](https://github.com/pypsa-meets-earth/documentation/blob/main/notebooks/validation/network_validation.ipynb):
    - overall lines length;
    - general grid topology;
    - ensure that the general structure of the grid model is appropriate, playing with `tol` values and augmentation options if needed.
 
2. Compare the [installed capacity](https://github.com/pypsa-meets-earth/documentation/blob/main/notebooks/validation/capacity_validation.ipynb) values 

3. Validate the [power demand](https://github.com/pypsa-meets-earth/documentation/blob/main/notebooks/validation/demand_validation.ipynb) values and profile.

4. Check that [hydro](https://github.com/pypsa-meets-earth/documentation/blob/main/notebooks/validation/hydro_generation_validation.ipynb), [solar and wind](https://github.com/pypsa-meets-earth/documentation/blob/main/notebooks/validation/renewable_potential_validation.ipynb) potentials have reasonable values

5. Simulate the actual [energy mix](https://github.com/pypsa-meets-earth/documentation/blob/main/notebooks/validation/validation_nigeria.ipynb). Look for detailed explanations in https://arxiv.org/abs/2209.04663, section 5.1.

Data availability and quality usually is the biggest concern. Some useful hints on the real-world validation example can be found in the [Nigeria validation](https://github.com/pypsa-meets-earth/documentation/blob/main/notebooks/validation/validation_nigeria.ipynb) notebook.

**Comment by davide-f** [comment]
Closing as not used
