### ISSUE TITLE
Add jupyter examples to readthedocs

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#226]
## Improving the documentation by adding notebook examples

New users might enter the documentation first before exploring any jupyter notebook example. We could link the jupyter notebook to the documentation as done in PyPSA https://github.com/PyPSA/PyPSA/blob/a5a62399e3deedade3f9759382987d0103d01f9d/doc/examples/create-nblinks

**Comment by davide-f** [comment]
Old issue
