### ISSUE TITLE
Reduce size of jupyter notebooks

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#227]
The jupyter notebooks take quite some space in the repo. Measure to reduce are given [here](https://stackoverflow.com/a/63326112/13573820). Here are some suggestions:
- Dataframes should be shown by df.head(5)
- Interactive plots probably not executed

One can check the final file size by executing at the end of each notebook `!ls -lh`

**Comment by Marydawn9** [comment]
Hi! Can I be assigned to this? :)

**Comment by davide-f** [comment]
> Hi! Can I be assigned to this? :)

Hi! Sure! We welcome new contributions and welcome to the community!
Looking forward to hearing from you, please for any hurdle comment or contact us

**Comment by euronion** [comment]
Possible extension (after fixing the current situation)

To prevent large files being added to the repository, one could think about adding a check to the Continous Integration (GitHub Actions or Pre-Commit CI). Such a check could prevent large files being added to the repository.

`pre-commit` has such a check for the `.pre-commit-config.yaml` file (see e.g. [here](https://github.com/PyPSA/pypsa-eur/blob/8b2ceda94840fd316ad606e537ba302a27ff0e8e/.pre-commit-config.yaml)):
```
  - id: check-added-large-files
  args: ['--maxkb=2000']
```

but I'm sure there are other options as well with GitHub Actions. :)

**Comment by pz-max** [comment]
@Marydawn9 If you are new to PyPSA and the whole GitHub thing, you might like to go through the hackathon that helps understand https://github.com/pypsa-meets-africa/pypsa-africa-hackathon

**Comment by pz-max** [comment]
close in favor of https://github.com/pypsa-meets-africa/pypsa-africa/issues/317
