### ISSUE TITLE
Undocumented dependency (java) for build_powerplants

### ISSUE THREAD

**Issue by euronion** [pz-max/pypsa-africa#279]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-africa/pypsa-africa/tree/main) branch or the latest [release](https://github.com/pypsa-meets-africa/pypsa-africa/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-africa` environment](https://github.com/pypsa-meets-africa/pypsa-africa/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug
The rule `build_powerplants` fails if java is not installed on the system.
Is this an undocumented dependency of `powerplantsmatching`?

I've installed java for now (Lubuntu, i.e. `sudo apt install default-jre`) to circumvent the problem.

## Error Message

Error produced
```
ERROR:powerplantmatching.duke:Java was not found on your system.
Traceback (most recent call last):
  File "/home/pypsa/miniconda3/envs/pypsa-africa/lib/python3.9/site-packages/powerplantmatching/duke.py", line 130, in duke
    run = sub.Popen(
  File "/home/pypsa/miniconda3/envs/pypsa-africa/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/pypsa/miniconda3/envs/pypsa-africa/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'java'

During handling of the above exception, another exception occurred:
```

**Comment by davide-f** [comment]
Thanks johannes!
As temporary fix, we may add it in our env file, but ai suggest you to add the issue on powerplantmatching repo as it is an issue of that repo.
I confirm that it uses some java API for comparing the data of different datasets

**Comment by oayana** [comment]
> ## Checklist
> * [x]  I am using the current [`main`](https://github.com/pypsa-meets-africa/pypsa-africa/tree/main) branch or the latest [release](https://github.com/pypsa-meets-africa/pypsa-africa/releases). Please indicate.
> * [x]  I am running on an up-to-date [`pypsa-africa` environment](https://github.com/pypsa-meets-africa/pypsa-africa/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.
> 
> ## Describe the Bug
> The rule `build_powerplants` fails if java is not installed on the system. Is this an undocumented dependency of `powerplantsmatching`?
> 
> I've installed java for now (Lubuntu, i.e. `sudo apt install default-jre`) to circumvent the problem.
> 
> ## Error Message
> Error produced
> 
> ```
> ERROR:powerplantmatching.duke:Java was not found on your system.
> Traceback (most recent call last):
>   File "/home/pypsa/miniconda3/envs/pypsa-africa/lib/python3.9/site-packages/powerplantmatching/duke.py", line 130, in duke
>     run = sub.Popen(
>   File "/home/pypsa/miniconda3/envs/pypsa-africa/lib/python3.9/subprocess.py", line 951, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/home/pypsa/miniconda3/envs/pypsa-africa/lib/python3.9/subprocess.py", line 1821, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'java'
> 
> During handling of the above exception, another exception occurred:
> ```

Hi @euronion,

As a workaround, you need to install jdk (https://jdk.java.net/java-se-ri/11) on your computer:

Next you have to add the path to your environment variables. Detailed explanation is available here:
https://www.java.com/en/download/help/path.html

I hope it works :)

**Comment by euronion** [comment]
Hi @oayana !

Thanks for the working workaround! :)

@davide-f : Yep, I'll do that. I figuerd I'll report it here (since we're using your fork of Koen's fork of the original PPM repo ;-). And also for other users who might encounter the problem.

`openjdk` seems available via `conda-forge` (https://anaconda.org/conda-forge/openjdk) Might be a good solution to just add it to the env. I'll give it a spin in the next days to see if that would work.

**Comment by davide-f** [comment]
> Hi @oayana !
> 
> Thanks for the working workaround! :)
> 
> @davide-f : Yep, I'll do that. I figuerd I'll report it here (since we're using your fork of Koen's fork of the original PPM repo ;-). And also for other users who might encounter the problem.
> 
> `openjdk` seems available via `conda-forge` (https://anaconda.org/conda-forge/openjdk) Might be a good solution to just add it to the env. I'll give it a spin in the next days to see if that would work.

Dependency just added in my fork; feel free to report it in the main repo :)

**Comment by davide-f** [comment]
I close this issue as it has been notified to the powerplantmatching repo and it has been incorporated in the branch we are using.
Thanks for the contribution @euronion ! :)
