### ISSUE TITLE
Verify HVDC lines

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#286]
## Verify and validate HVDC lines

HVDC lines should be addressed and verified along the code.
For simplicity assumptions, lines have been assumed to be mostly AC, but this assumption can no longer be considered.

The code shall be revised to remove assumptions of AC lines, especially when we want to go global.

Such main assumptions are made in the [build_osm_network script](https://github.com/pypsa-meets-africa/pypsa-africa/blob/main/scripts/build_osm_network.py); generally the "DC" status is set to false by default but that shall be revised
DC nodes shall be distinguished from AC nodes.

In particular, in the function merge_stations_lines_by_station_id_and_voltage, AC nodes shall be distinguished from DC nodes
https://github.com/pypsa-meets-africa/pypsa-africa/blob/dff3930706a967e842e9e7427f7c01b0532bcf0d/scripts/build_osm_network.py#L422

**Comment by ekatef** [comment]
An attempt to filter out HVDC lines seems to give quite satisfactory results for Brazil:

<img width="546" alt="image" src="https://user-images.githubusercontent.com/30229437/163876145-64284926-5dc2-484c-8bf6-3534c642d777.png">

_Blue corresponds to the (supposedly) three-phase lines AC, red to the DC lines, grey denotes areas where data to distinguish between AC and DC are not available. Line thickness is set according to the voltage value._

The validation data are available as [pdf](http://www.ons.org.br/_layouts/download.aspx?SourceUrl=http://www.ons.org.br/Mapas/Mapa%20Sistema%20de%20Transmissao%20-%20Horizonte%202024.pdf) via site of the national system operator and give a pretty similar outline of the HVDC lines (dark colors and "cc" for "corrente contínua" in the legend).

However, results for US and China look rather discouraging:

<img width="889" alt="image" src="https://user-images.githubusercontent.com/30229437/163877446-ddb71726-ae9a-41f0-8332-9048f60c6d9f.png">

<img width="864" alt="image" src="https://user-images.githubusercontent.com/30229437/163878227-b8ef0d86-1c8b-46eb-a101-2ff0d982de5f.png">

Under the used approach it seems that there are not enough data to distinguish between DC and AC. The main parameter used was a ratio `r` defined as `number of cables` / `number of circuits` while the voltage value is used as an additional check. However, data required to calculate `r` are either missed (grey color) or correspond to a three phase AC power grid (blue color). There are some grid elements with `r == 1` (in red) or `r == 2` (in green) but they are very short.

Some additional information seems to be highly desirable to improve capture of HVDC by the model. Probably, it makes sense to use data on generators for these purpose? Or even add some data on an approximate geographical location of DC lines as longitude/latitude range...

**Comment by pz-max** [comment]
Awesome @ekatef :) .. really love the images that you produced. Do you like to author a post in future raising the awareness of the data quality & motivate people to contribute to OSM/our initiative?

Hope that AC/DC labelling issue can be improved with data fusion/prediction approaches. Guess most are though AC anyways…

Regarding US grid data, the breakthrough energy project provides/uses fantastic data. https://science.breakthroughenergy.org/ Is the US data already open available @fneum @FabianHofmann ?

**Comment by fneum** [comment]
https://zenodo.org/record/3530899#.Yl4_ci_Ra-o

https://arxiv.org/pdf/2002.06155.pdf

I think the route is to import this dataset with powersimdata and use the new export_to_PyPSA function https://github.com/Breakthrough-Energy/PowerSimData/blob/develop/powersimdata/input/export_data.py#L289

**Comment by ekatef** [comment]
Hi @pz-max, of course I'ld be happy to write a post explaining why data quality/availability is important from the perspective of energy transition facilitation across the globe.

Hi @fneum, many thanks for the links. The project looks really impressive and I absolutely agree that it would be great to incorporate these data into the PyPSA-Earth.

**Comment by ekatef** [comment]
Playing around with different filters has given the following results.

1. `Frequency == 0` seems to be the best way to filter out the HVDC lines. Taking Africa as an example:

![africa2_lines_lines_raw_freq_col_thick_lines](https://user-images.githubusercontent.com/30229437/169293751-5b80863b-8181-4615-86e0-37a328a9804f.jpg)

Legend:
red - 0 Hz
blue - 50 Hz
grey - NA

The picture is quite consistent with the data of the Southern African Power Pool.

![SAPP GRID MAP 2021 v2](https://user-images.githubusercontent.com/30229437/169292779-f07a27fc-ff3c-4918-9c81-2ea9a2d449e0.jpg)

According to  [Wikipedia ](https://en.wikipedia.org/wiki/List_of_HVDC_projects#Africa) and [Arcia-Garibaldi et al. (2018)](https://www.sciencedirect.com/science/article/pii/S1364032118304416) there are currently four DC parts which all were filtered from OSM data.

2. The `name` field is good to have when a deeper look into DC grid is needed. HVDC lines are usually supplemented by labels (in contrast to ordinary AC grid). However, some preliminary knowledge is needed to use names filtering as `name` can contain some geography-related link instead of direct "HVDC" indication (e.g.  `"Caprivi Link"`). So, the `name` field is a nice option to have. But seems to be not a good idea to use it for initial automated filtering.

3. The cables-to-circuits ration could be probably applies to find non-standard AC lines. But here I think more validation is needed.

**Comment by davide-f** [comment]
Copied here from #324 

> Our base_network script does not properly address links (e.g. HVDC lines) as it should; see as a reference the [base_network in pypsa-eur](https://github.com/PyPSA/pypsa-eur/blob/master/scripts/prepare_network.py).
> The links and converters should be added to properly simulate HVDC lines.
> 
> To do so, there are two options in my view:
> 
> in the base_network script, process the lines dataframe to separate the HVDC lines
> move the filtering before in the cleaning_osm_data to create the additional files for links and converters. This second option I think is the more elegant, though longer

**Comment by davide-f** [comment]
As discussed with @ekatef , the suggested steps to include HVDC lines is:
1. in clean_osm_data, first of all, identify DC lines by using frequency=0
2. in clean_osm_data, distinguish "lines.csv" as only AC lines, and create the "links.csv" for DC lines, as in PyPSA-Eur
3. verify in osm_build_network if anything is needed or simply "copy and paste" links.csv into a different folder in agreement with the other files
4. modify base_network to include the links, see [base_network in PyPSA-Eur](https://github.com/PyPSA/pypsa-eur/blob/master/scripts/base_network.py)
5. Vefify (and pray XD) that everything works

**Comment by davide-f** [comment]
@ekatef Probably in the point 3. there is the need to verify the grouping mechanism of the function `merge_stations_lines_by_station_id_and_voltage`, as mentioned in the first comment of this issue

> ## Verify and validate HVDC lines
> HVDC lines should be addressed and verified along the code. For simplicity assumptions, lines have been assumed to be mostly AC, but this assumption can no longer be considered.
> 
> The code shall be revised to remove assumptions of AC lines, especially when we want to go global.
> 
> Such main assumptions are made in the [build_osm_network script](https://github.com/pypsa-meets-africa/pypsa-africa/blob/main/scripts/build_osm_network.py); generally the "DC" status is set to false by default but that shall be revised DC nodes shall be distinguished from AC nodes.
> 
> In particular, in the function merge_stations_lines_by_station_id_and_voltage, AC nodes shall be distinguished from DC nodes
> 
> https://github.com/pypsa-meets-africa/pypsa-africa/blob/dff3930706a967e842e9e7427f7c01b0532bcf0d/scripts/build_osm_network.py#L422

**Comment by ekatef** [comment]
@davide-f I'll check :) Thank you for the hint!

**Comment by ekatef** [comment]
Hey @davide-f, studying of the `merge_stations_lines_by_station_id_and_voltage( )` has been very helpful. I see the groupings you have mentioned but not sure if my understanding of the underlying modelling assumptions is correct.

It seems  there is no a special `Converter` component in PyPSA  (converters in PyPSA-Eur are introduced as `Links`). So, we need to implement our own modelling approach for converters, and it feels quite natural to use generalisation of a transformer model developed in PyPSA-Africa. 

If I'm not mistaken, the only major difference between a transformer and a converter is that the latter actually converts DC to AC with an optional voltage change. In case that's correct, for converters we'll need an additional grouping by `"dc"` flag while other assumptions can be taken from the transformer model. Namely:

1) the transformers are modelled as lines connecting buses with different voltages;

2) in the final of pre-processing, there can't be more than two buses with the same station_id and the same voltage;

3) it's possible that the same bus_id has multiple dataframe entries with different voltage levels but slightly different locations (with the difference controlled by `delta_lon` and `delta_lat` parameters).

Could you please let me know if this sounds reasonable for you? :)

**Comment by pz-max** [comment]
Hi @ekatef ,
Regarding modelling AC&DC networks. The minimal example in PyPSA might be helpful: https://pypsa.readthedocs.io/en/latest/examples/ac-dc-lopf.html

This answers 1). On how transformers and converters are modelled. Transformers are modelled as lines (not controllable) & converters are modelled as links (controllable), see the PyPSA documentation for more details. Regarding 2). Makes sense. Not sure about 3), a bus should be unique, but a station can include multiple buses.

Hope that helps a bit.

**Comment by ekatef** [comment]
Hi @pz-max,
Many thanks for the link and the comments. Indeed, it helps a lot :) Actually, the PyPSA docs are a great starting point to understand the fundamentals I'm interested in.

As for details of transformers implementations, I see that the PyPSA-Europe model is utilising the `Transformer` component [directly](https://github.com/PyPSA/pypsa-eur/blob/6c633cf6eb46fd6cb31475b64755c1b11ed584ec/scripts/base_network.py#L564-L570), while the PyPSA-Africa seems to implement a different approach where data on transformers are appended to the `lines` data frame

https://github.com/pypsa-meets-africa/pypsa-africa/blob/d86fed5a6dee9e6e55b9ceed6ef20042ce6fab16/scripts/build_osm_network.py#L548-L549

https://github.com/pypsa-meets-africa/pypsa-africa/blob/d86fed5a6dee9e6e55b9ceed6ef20042ce6fab16/scripts/base_network.py#L328-L331

I wonder if it would be a proper approach to introduce converters in a similar way... Let say:

```python
converters = get_converters(buses, lines)
links = pd.concat([links, converters], ignore_index=True)
```
What do you think?

**Comment by pz-max** [comment]
Ups Transformers are indeed modeled as lines. See my changes from the previous comment which I corrected now.

Your implementation idea looks good. Going along the PyPSA-Eur style is always good. Just be aware if you introduce new components sometimes the bus & station indexing/numbering might change. Looking forward to this PR.

**Comment by ekatef** [comment]
@pz-max, ok, many thanks for the update. If I'm not completely wrong with the implementation strategy, it means that you and @davide-f have done an excellent development work :) The code is very clear and pretty self-explaining.

Thank you for the hint about indexing!

**Comment by davide-f** [comment]
So, totally agree on what discussed. Also according to the discussion we had this morning, I will resume altogether my comments.

> 2. in the final of pre-processing, there can't be more than two buses with the same station_id and the same voltage;

I confirm that: all buses with the same station id and voltages are grouped together and 

> 3. it's possible that the same bus_id has multiple dataframe entries with different voltage levels but slightly different locations (with the difference controlled by `delta_lon` and `delta_lat` parameters).

As max said, each bus is unique, conversely to stations. Buses of the same station_id are slightly moved (by the deltas) to make them be visible on the map if we zoom in, just for that purpose.

> I wonder if it would be a proper approach to introduce converters in a similar way... Let say:
> 
> ```python
> converters = get_converters(buses, lines)
> links = pd.concat([links, converters], ignore_index=True)
> ```

As discussed, I think here we should go for a simple approach and refine the transformers and converters later on.
Hence, feel free to propose what you think it is the simplest approach.
Soething like you proposed or even simpler (no converters) may be duable, yet later the converters shall be better added in a subsequent PR or this one.

Sorry for the delay

**Comment by ekatef** [comment]
@davide-f, many thanks for the discussion and detailed comments. And I don't think it was any delay :)

> As discussed, I think here we should go for a simple approach and refine the transformers and converters later on.
> Hence, feel free to propose what you think it is the simplest approach.
> Soething like you proposed or even simpler (no converters) may be duable, yet later the converters shall be better added in a subsequent PR or this one.

Great! Very much like the stepwise approach you propose. Currently I'm experimenting with the implementation of a simplified converters model but probably it's a good idea to drop them at this step for the sake of functionality...

As for simplifications, I absolutely don't think that introducing them into a model is always bad :) Each model is an idealisation and the trick is to adjust it's levels of details according to the question this model is intended to answer.

**Comment by davide-f** [comment]
If you are half way for the implementation of converters and feel like including it here, go for it if you feel like :)

**Comment by ekatef** [comment]
@davide-f, it was actually a very good idea to drop converters at first :) I'm a bit struggling with network topology after simplification. The whole DC-line gets lost after `simplify_network` has been applied. That seems to be a result of "reducing multi-hop HVDC connections to a single link" which is fulfilled as a part of simplification. Do I understand properly that the cure is to fix the connections of the DC line to AC network on the both ends of the DC line?

Pictures before and after simplification are bellow. Although the latter at the moment looks rather terrifying...
[elec.nc_map3.pdf](https://github.com/pypsa-meets-africa/pypsa-africa/files/8838698/elec.nc_m

[elec_s.nc_map3.pdf](https://github.com/pypsa-meets-africa/pypsa-africa/files/8838699/elec_s.nc_map3.pdf)
ap3.pdf)

**Comment by ekatef** [comment]
@davide-f, thank you for the discussion. As always, it was incredibly helpful and encouraging :)

The resulted base.nc  network now looks like that

![base nc](https://user-images.githubusercontent.com/30229437/172933155-bb0c8886-248b-4c9e-bc24-df5046fcfd61.png)

It's even possible to run a network simplification with the following result (not sure why it works as the convertes are commented-out at the moment):

![elec_s nc](https://user-images.githubusercontent.com/30229437/172933189-8a996b4a-55df-4ef0-a2e8-577da9639c08.png)

But clustering crashes with an error complaining on some carriers discrepancies in a cluster `AssertionError: In Bus cluster carrier the values of attribute carrier do not agree` (a full listing is bellow). Do you have any ideas what does it mean? I see that converters in PyPSA-Europe are modelled with "B2B" carrier

https://github.com/PyPSA/pypsa-eur/blob/829c1055f7d434b5e181f3b3ae42fac1d0775602/scripts/base_network.py#L155-L157

Probably, that is the way to fix this attributes mismatch?

PS The error message looks like that:
``` bash
INFO:snakemake.logging:
This is the repository path:  /~/Documents/_github_/pypsa-africa
Had to go 0 folder(s) up.
INFO:pypsa.io:Imported network elec_s.nc has buses, carriers, generators, lines, links, loads, storage_units
WARNING:pypsa.components:Warning, sub network 0 contains buses with mixed carriers! Value counts:
AC    26
DC     1
Name: carrier, dtype: int64
Traceback (most recent call last):
  File "/~/Documents/_github_/pypsa-africa/.snakemake/scripts/tmp0ik9z8s9.cluster_network.py", line 578, in <module>
    clustering = clustering_for_n_clusters(
  File "/~/Documents/_github_/pypsa-africa/.snakemake/scripts/tmp0ik9z8s9.cluster_network.py", line 449, in clustering_for_n_clusters
    clustering = get_clustering_from_busmap(
  File "/~/opt/miniconda3/envs/pypsa-africa/lib/python3.10/site-packages/pypsa/networkclustering.py", line 364, in get_clustering_from_busmap
    buses, linemap, linemap_p, linemap_n, lines, lines_t = get_buses_linemap_and_lines(
  File "/~/opt/miniconda3/envs/pypsa-africa/lib/python3.10/site-packages/pypsa/networkclustering.py", line 321, in get_buses_linemap_and_lines
    buses = aggregatebuses(network, busmap, bus_strategies)
  File "/~/opt/miniconda3/envs/pypsa-africa/lib/python3.10/site-packages/pypsa/networkclustering.py", line 205, in aggregatebuses
    .agg(strategies)
  File "/~/opt/miniconda3/envs/pypsa-africa/lib/python3.10/site-packages/pandas/core/groupby/generic.py", line 869, in aggregate
    result = op.agg()
  File "/~/opt/miniconda3/envs/pypsa-africa/lib/python3.10/site-packages/pandas/core/apply.py", line 168, in agg
    return self.agg_dict_like()
  File "/~/opt/miniconda3/envs/pypsa-africa/lib/python3.10/site-packages/pandas/core/apply.py", line 475, in agg_dict_like
    results = {
  File "/~/opt/miniconda3/envs/pypsa-africa/lib/python3.10/site-packages/pandas/core/apply.py", line 476, in <dictcomp>
    key: obj._gotitem(key, ndim=1).agg(how) for key, how in arg.items()
  File "/~/opt/miniconda3/envs/pypsa-africa/lib/python3.10/site-packages/pandas/core/groupby/generic.py", line 287, in aggregate
    return self._python_agg_general(func, *args, **kwargs)
  File "/~/opt/miniconda3/envs/pypsa-africa/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1481, in _python_agg_general
    result = self.grouper.agg_series(obj, f)
  File "/~/opt/miniconda3/envs/pypsa-africa/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 981, in agg_series
    result = self._aggregate_series_pure_python(obj, func)
  File "/~/opt/miniconda3/envs/pypsa-africa/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 1005, in _aggregate_series_pure_python
    res = func(group)
  File "/~/opt/miniconda3/envs/pypsa-africa/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1467, in <lambda>
    f = lambda x: func(x, *args, **kwargs)
  File "/~/opt/miniconda3/envs/pypsa-africa/lib/python3.10/site-packages/pypsa/networkclustering.py", line 59, in consense
    assert (
AssertionError: In Bus cluster carrier the values of attribute carrier do not agree:
Bus
7     AC
12    AC
34    AC
44    AC
45    AC
52    AC
53    AC
54    AC
55    DC
71    DC
96    AC
Name: carrier, dtype: object
```

**Comment by davide-f** [comment]
@ekatef great update!

In our simplify_network, simplify_links function and the simplify_network have never been tested with links.
That may partially be the issue, as well as in your network lines seem to be removed for some reason.
That may lead to issues as well.
Maybe it is better to check first the integrity of the network: hence that lines and links are connected.
You could start by checking the csvs (output of build_osm_network) and see f the lines are properly matched and if not start debug why that does not occur.

**Comment by davide-f** [comment]
@pz-max @fneum may you have some other suggestions?

**Comment by fneum** [comment]
Buses clustered need to agree on the same carrier. That leads to the issue here.

**Comment by ekatef** [comment]
@davide-f, it sounds like glimpse of light in the darkness :) Thank you so much for the guidance.

@fneum, many thanks for the hint. It's really helpful.

**Comment by ekatef** [comment]
I have checked the csv-files calculated by `build_osm_network` and it looks like lines and buses are matched properly. The problems with grid topology are likely caused by the quality of raw osm data for CDR:

![whole_raw_dataset_CD](https://user-images.githubusercontent.com/30229437/173447474-07a5785a-b358-4eff-9088-2481ea0ffa35.png)

I have also done a little test for Namibia with the following result for `base.nc`:

![base nc](https://user-images.githubusercontent.com/30229437/173447573-5758fa5d-796d-443e-8505-86bd450c0898.png)

Setting buses and links carries in `base_network` back to `"AC"` allows to run the workflow up to the solving part where an error is thrown due to a missing link attribute `efficiency_0_coors` (the error listing is bellow).

@davide-f, do you have any ideas what does it mean? Generally, I very much like your idea to go step-by-step in modifying workflow but it's difficult for me to define a point where we can finalise the fist iteration.

``` bash
INFO:snakemake.logging:
INFO:pypsa.io:Imported network elec_s_6_ec_lcopt_Co2L-3H.nc has buses, carriers, generators, global_constraints, lines, links, loads, storage_units, stores
INFO:pypsa.linopf:Prepare linear problem
Traceback (most recent call last):
  File "~/_github_/pypsa-africa/.snakemake/shadow/tmp6sazm5_w/.snakemake/scripts/tmp3_0ka5m2.solve_network.py", line 352, in <module>
    n = solve_network(
  File "~/_github_/pypsa-africa/.snakemake/shadow/tmp6sazm5_w/.snakemake/scripts/tmp3_0ka5m2.solve_network.py", line 313, in solve_network
    ilopf(
  File "/Users/ekaterina/opt/miniconda3/envs/pypsa-africa/lib/python3.10/site-packages/pypsa/linopf.py", line 1614, in ilopf
    status, termination_condition = network_lopf(n, snapshots, **kwargs)
  File "/Users/ekaterina/opt/miniconda3/envs/pypsa-africa/lib/python3.10/site-packages/pypsa/linopf.py", line 1458, in network_lopf
    fdp, problem_fn = prepare_lopf(
  File "/Users/ekaterina/opt/miniconda3/envs/pypsa-africa/lib/python3.10/site-packages/pypsa/linopf.py", line 1116, in prepare_lopf
    define_nodal_balance_constraints(n, snapshots)
  File "/Users/ekaterina/opt/miniconda3/envs/pypsa-africa/lib/python3.10/site-packages/pypsa/linopf.py", line 460, in define_nodal_balance_constraints
    eff = get_as_dense(n, "Link", f"efficiency{i}", sns)
  File "/Users/ekaterina/opt/miniconda3/envs/pypsa-africa/lib/python3.10/site-packages/pypsa/descriptors.py", line 182, in get_switchable_as_dense
    varying_i = pnl[attr].columns
KeyError: 'efficiency_0_coors'
```
