### ISSUE TITLE
Need to update world_iso country and continent list

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#290]
Looking at the data of [synde](https://github.com/euronion/synde/blob/master/config/regions.yaml), [our_world_iso](https://github.com/pypsa-meets-africa/pypsa-africa/blob/44b6236b641640b6502632df60773b30e4aa2f74/scripts/config_osm_data.py), and [wikipedia](https://en.wikipedia.org/wiki/List_of_sovereign_states_and_dependent_territories_by_continent_(data_file)), it seems our world_iso is not complete... We should update our world_iso to be complete and also adapt the correct continent naming

_Originally posted by @pz-max in https://github.com/pypsa-meets-africa/pypsa-africa/pull/275#discussion_r829535718_

**Comment by davide-f** [comment]
Closed by #330
