### ISSUE TITLE
Harmonize Coordinate Reference Systems (CRS) and set them as configuration options

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#297]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-africa/pypsa-africa/tree/main) branch or the latest [release](https://github.com/pypsa-meets-africa/pypsa-africa/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-africa` environment](https://github.com/pypsa-meets-africa/pypsa-africa/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

Across all scripts, different Coordinate Reference Systems (CRS) have been used and there is confusion; they should be harmonized with criterion.
In particular, we need CRS for GIS analysis. Since we are interested into distances, EPSG reference type seems the most appropriate, [reference](https://docs.qgis.org/2.8/en/docs/gentle_gis_introduction/coordinate_reference_systems.html) and [reference 2](https://www.nceas.ucsb.edu/sites/default/files/2020-04/OverviewCoordinateReferenceSystems.pdf).
In particular, when it comes to CRS valid worldwide, EPSR:4326 may be the recommended and we are mainly using it, however it is in cylindrical reference (curved surface), thus it is not suitable when we need to measure distances in km.
For metric distances, we can use EPSG:3857, which seems to be the most appropriate.

Across the code, there are also different CRS that have been used and they shall be cleansed (refuse from PyPSA-Eur).
Moreover, I would like to have them as options, such as crs (EPSG:4326) and crs_metric (EPSG:3857) that can be customized.
Note that this does not mean to blindly substitute the optional value everywhere in the code, but where it is needed: when we set a crs on a loaded geodataframe from an external source (e.g. gadm) the crs may be specific to that external resource.
We shall specify the crs for our processed data.
That's why I some crs may be still hard coded, but it shall be discussed.

**Comment by euronion** [comment]
Important thing to do indeed. The projection used in PyPSA-EUR `EPSG:3035` is only accurate for Europe.

Correction: `EPSG`-CRSs (and `ESRI`-CRSs) are commonly used identifiers for coordinate reference systems. Not all CRSs are suited for our task at hand, so "EPSG reference type seems the most appropriate," ma be misleading.

I would disencourage the use of Mercator projection ( `EPSG:3857`). Mercator has large area distortions, is a CRS created for navigation and not equal-area, making it unsuitable for area comparison and analysis. I suggest to use Global Mollweide `ESRI:54009` ([epsg.io](https://epsg.io/54009), [arcgis documentation](https://desktop.arcgis.com/en/arcmap/latest/map/projections/mollweide.htm) ) instead.

With regards to hard-coding vs. parameterisation of the CRS: I agree that some CRS need to be hard-coded to represent the CRS of input we are taking from external sources. When handling CRS it is important that the CRS is consistent and compatible across all georeference data used at the same time. I think that is a good point to prefer hard-coded CRS over parameterisation.

**Comment by davide-f** [comment]
Totally agree, and thanks for adding clarification, I may have been too coincise in the suggestion.

The mercator projection is only used internally when we need to calculate distances in meters or areas of shapes, no other reason.
