### ISSUE TITLE
Explore speed benefit from replacing "rasterio" with "xagg" -> raster2polygon operations

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#336]
[xagg](https://github.com/ks905383/xagg) promises to be faster than rasterio when summing raster data (eg. 10x10km) of polygon shapes. An interesting task would be to explore the performance benefits since these operations are quite time-consuming.

One example where this could be tested: https://github.com/pypsa-meets-africa/pypsa-africa/blob/1fd74e703d507a0105eaca89981efffa6ea021db/scripts/build_shapes.py#L454-L470

If the test is positive we might also enhance the performance of [Atlite](https://github.com/PyPSA/atlite) accordingly which uses this type of function to sum a renewable raster into polygons & also use it to exclude rasters (e.g. a protected area should reduce the sum)

**Comment by davide-f** [comment]
With PR #650 this PR can be closed. Feel free to reopen it if deemed useful
