### ISSUE TITLE
'float' object has no attribute bug caused by osm part in build_powerplants.py

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#370]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-africa/pypsa-africa/tree/main) branch or the latest [release](https://github.com/pypsa-meets-africa/pypsa-africa/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-africa` environment](https://github.com/pypsa-meets-africa/pypsa-africa/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug
@AnasAlgarei and I experience a little bug related to the OpenStreetMap powerplant part in build_powerplants (see error message below). We comment the osm part out in the snakefile and the function for a hard fix. Debugging and fixing this properly is desired even though we are not using the OSM data yet.

## Error Message

![image](https://user-images.githubusercontent.com/61968949/171997552-e233111d-f415-42fe-b7a5-3f6829ab8461.png)

**Comment by davide-f** [comment]
Ok! Though I think the simple fix is to make sure that the column or each processed element is a string.
Let's keep the issue for the moment
