### ISSUE TITLE
Bug in clustering or simplify network lead to bus aggregated to two nodes

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#383]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-africa/pypsa-africa/tree/main) branch or the latest [release](https://github.com/pypsa-meets-africa/pypsa-africa/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-africa` environment](https://github.com/pypsa-meets-africa/pypsa-africa/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

@martacki contributed the great figures below. She found a bug:
"Hmm, something with the clustering is broken, there exists a bus that's aggregated to 2 nodes
I mean, I don't think it's a bug, I think it's related to the seed of k-means. Though this should not happen."

![Screenshot from 2022-06-16 11-40-08](https://user-images.githubusercontent.com/61968949/174052402-ca34c4f7-bb1b-456c-8461-1fab73c24985.png)

![Screenshot from 2022-06-16 11-40-17](https://user-images.githubusercontent.com/61968949/174052395-a80a883c-c156-4b6d-b0f2-46e235f02065.png)

I will play a bit with the initial k-means values to see if the situation improves.

**Comment by martacki** [comment]
Hey @pz-max I don't think it's a bug - I meant that this wouldn't happen if we'd apply the clustering properly. For this figure I was hacking the networks to represent how the clustering *should* work.
With "Though this should not happen." I meant this **wouldn't** happen if properly applied, meaning without the hack I was using.
If you want, you can verify my statement by:
1 creating the networks `elec_s54_54.nc`, `elec_s54_14.nc` and `elec_s54_4.nc`. That way you can work around the kmeans seed randomness
2 adapting the paths of the networks, onshore_regions and busmaps in the ipynb to hold the fixed 54 s-wildcard
3 execute
Let me know if you need assistance, I think this should work but of course I might miss sth
