### ISSUE TITLE
Unify save_to_geojson

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#387]
Regarding simplify_network and cluster_network, I think we miss:
- we also use here a function save_to_geojson that is like a duplicate of save_to_geojson in the helpers. I think we should have only a single function to do so, though their formatting shall be crosschecked or aligned.

_Originally posted by @davide-f in https://github.com/pypsa-meets-africa/pypsa-africa/pull/386#pullrequestreview-1010484207_

**Comment by davide-f** [comment]
Done; to be reopened if something is missing
