### ISSUE TITLE
Add aggregation strategies for conventionals and harmonize code

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#390]
## Describe the feature you'd like to see

There is no proper aggregation strategy for conventional carriers. A PyPSA-Eur PR fixed this https://github.com/PyPSA/pypsa-eur/pull/379. Another PR which is still open (update: now closed) harmonizes the aggregation strategies in: https://github.com/PyPSA/pypsa-eur/pull/380. Let's adopt these great improvements.

**Comment by ekatef** [comment]
It looks like this issue has been addressed by #402 :)

**Comment by davide-f** [comment]
Closing as it seems complete. Reopen if appropriate
