### ISSUE TITLE
Cut off sentence in the tutorial rst

### ISSUE THREAD

**Issue by Tomkourou** [pz-max/pypsa-africa#410]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-africa/pypsa-africa/tree/main) branch or the latest [release](https://github.com/pypsa-meets-africa/pypsa-africa/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-africa` environment](https://github.com/pypsa-meets-africa/pypsa-africa/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

Not a bug per say but I just noticed that the [tutorial.rst](https://github.com/pypsa-meets-africa/pypsa-africa/blob/main/doc/tutorial.rst) seems to be missing a part at the end. 

On manual testing you write: 

"Manual test of specific scripts

The scripts in the scripts folder are build so that they can be easily run and tested even without the snakemake procedure. Therefore, to test the specific functionality of"

I believe the last sentence is somehow unfinished.

**Comment by pz-max** [comment]
Hi @Tomkourou, good spot! We will fix that in the next days :+1:
