### ISSUE TITLE
Missed projection description for a hydrobasins shapefile

### ISSUE THREAD

**Issue by ekatef** [pz-max/pypsa-africa#440]
I have been playing with the workflow for Central Asia and have faced an issue when (unintentionally) have updated the hydrobasins data. 

## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-africa/pypsa-africa/tree/main) branch or the latest [release](https://github.com/pypsa-meets-africa/pypsa-africa/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-africa` environment](https://github.com/pypsa-meets-africa/pypsa-africa/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

The `hydrobasins` folder was deleted by mistake and restored along others model common data via zenodo https://sandbox.zenodo.org/record/1016522. After that generating hydro profiles has resulted in an error related to a loss of the CRS data for the basin shapefiles (the error listing is attached bellow). It looks like the problem was caused by a fact that atlite expects the basin [shapefiles](https://en.wikipedia.org/wiki/Shapefile) to have a projections descriptions in a `prj` file which is by some reasons missed from the used shapefile set.

The global basins data are currently not available from the source [hydrosheds page](https://www.hydrosheds.org/products/hydrobasins), there are only data by macro-regions. An attempt to use the Asia basin dataset has lead to some troubles with loss inflow time-series for some buses `AssertionError: 'resources/renewable_profiles/profile_hydro.nc' is missing inflow time-series for at least one bus: 1218, 605, 843`. I suspect, the reason could be presence of some catchments in the cutout which belong to the European domain and thus are not included into the basin data for Asia.  

The fix was to use the initial global dataset adding a projection file copied from the Asia dataset and renamed according to the global conventions (e.g. "hybas_world_lev06_v1c.prj").

By the way, trying to resolve the issue with the projections I had to look into calculation of the indicator matrix which normalisation sometimes leads to NaNs. And it looks like the NaNs fix https://github.com/davide-f/atlite/blob/cfcfd8b46bf2c79fc12da092188f9d5ffac6e517/atlite/convert.py#L808-L812 is needed when some considered basins do not contained in the used cutout which by no means is linked with any problems in the shapefile. 

If I understand properly, the indicator matrix is essentially a table formatted according to `scipy.sparse.lil_matrix` convections where the columns correspond to the basins while the rows to the cells of the cutout grid. Thus, the sum across a single column is 1 if the corresponding basin is completely included into the cutout area while for the basins beyond the cutout domain the column sum is zero. The issue with NaNs appears if there is division by zero column sums and is a natural consequence of moving to the global basins dataset. Could it probably be a good idea to replace the warning with an info message?

## Error Message

```bash
INFO:snakemake.logging:
[Sat Aug 13 16:21:37 2022]
INFO:snakemake.logging:[Sat Aug 13 16:21:37 2022]
rule build_renewable_profiles:
    input: networks/base.nc, resources/natura.tiff, data/copernicus/PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif, data/gebco/GEBCO_2021_TID.nc, resources/shapes/country_shapes.geojson, resources/shapes/offshore_shapes.geojson, data/hydro_capacities.csv, data/eia_hydro_annual_generation.csv, resources/powerplants.csv, resources/bus_regions/regions_onshore.geojson, cutouts/casr-2015-era5.nc
    output: resources/renewable_profiles/profile_hydro.nc
    log: logs/build_renewable_profile_hydro.log
    jobid: 19
    benchmark: benchmarks/build_renewable_profiles_hydro
    reason: Missing output files: resources/renewable_profiles/profile_hydro.nc; Input files updated by another job: networks/base.nc, resources/bus_regions/regions_onshore.geojson, resources/powerplants.csv
    wildcards: technology=hydro
    resources: tmpdir=/var/folders/qn/vpndfm21795ckkq89np1ckp40000gn/T, mem=20000
INFO:snakemake.logging:rule build_renewable_profiles:
    input: networks/base.nc, resources/natura.tiff, data/copernicus/PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif, data/gebco/GEBCO_2021_TID.nc, resources/shapes/country_shapes.geojson, resources/shapes/offshore_shapes.geojson, data/hydro_capacities.csv, data/eia_hydro_annual_generation.csv, resources/powerplants.csv, resources/bus_regions/regions_onshore.geojson, cutouts/casr-2015-era5.nc
    output: resources/renewable_profiles/profile_hydro.nc
    log: logs/build_renewable_profile_hydro.log
    jobid: 19
    benchmark: benchmarks/build_renewable_profiles_hydro
    reason: Missing output files: resources/renewable_profiles/profile_hydro.nc; Input files updated by another job: networks/base.nc, resources/bus_regions/regions_onshore.geojson, resources/powerplants.csv
    wildcards: technology=hydro
    resources: tmpdir=/var/folders/qn/vpndfm21795ckkq89np1ckp40000gn/T, mem=20000

INFO:snakemake.logging:
WARNING:country_converter.country_converter:Hawaiian Trade Zone not found in regex
WARNING:country_converter.country_converter:Netherlands Antilles not found in regex
WARNING:country_converter.country_converter:U.S. Pacific Islands not found in regex
WARNING:country_converter.country_converter:U.S. Territories not found in regex
WARNING:country_converter.country_converter:Wake Island not found in regex
INFO:__main__:Hydro normalization mode eia
Determine upstream basins per plant: 1045it [00:38, 27.42it/s]
~/opt/miniconda3/envs/pypsa-africa/lib/python3.9/site-packages/scipy/sparse/_base.py:665: RuntimeWarning: invalid value encountered in divide
  return np.true_divide(self.todense(), other)
WARNING:atlite.convert:Inflows normalization lead to np.nan values; check the hydrobasins. Nan values set to 0.0
INFO:atlite.convert:Convert and aggregate 'runoff'.
Traceback (most recent call last):
  File "~/Documents/_github_/pypsa-africa/.snakemake/scripts/tmpr696eozw.build_renewable_profiles.py", line 396, in <module>
    inflow = correction_factor * func(capacity_factor=True, **resource)
  File "~/opt/miniconda3/envs/pypsa-africa/lib/python3.9/site-packages/atlite/convert.py", line 827, in hydro
    basins.shapes.to_crs(dict(proj="cea")).area
  File "~/opt/miniconda3/envs/pypsa-africa/lib/python3.9/site-packages/geopandas/geoseries.py", line 1117, in to_crs
    self.values.to_crs(crs=crs, epsg=epsg), index=self.index, name=self.name
  File "~/opt/miniconda3/envs/pypsa-africa/lib/python3.9/site-packages/geopandas/array.py", line 750, in to_crs
    raise ValueError(
ValueError: Cannot transform naive geometries.  Please set a crs on the object first.
[Sat Aug 13 16:23:07 2022]
INFO:snakemake.logging:[Sat Aug 13 16:23:07 2022]
Error in rule build_renewable_profiles:
    jobid: 19
    output: resources/renewable_profiles/profile_hydro.nc
    log: logs/build_renewable_profile_hydro.log (check log file(s) for error message)

ERROR:snakemake.logging:Error in rule build_renewable_profiles:
    jobid: 19
    output: resources/renewable_profiles/profile_hydro.nc
    log: logs/build_renewable_profile_hydro.log (check log file(s) for error message)

RuleException:
CalledProcessErrorin line 335 of ~/Documents/_github_/pypsa-africa/Snakefile:
Command 'set -euo pipefail;  ~/opt/miniconda3/envs/pypsa-africa/bin/python3.9 ~/Documents/_github_/pypsa-africa/.snakemake/scripts/tmpr696eozw.build_renewable_profiles.py' returned non-zero exit status 1.
  File "~/Documents/_github_/pypsa-africa/Snakefile", line 335, in __rule_build_renewable_profiles
  File "~/opt/miniconda3/envs/pypsa-africa/lib/python3.9/concurrent/futures/thread.py", line 58, in run
ERROR:snakemake.logging:RuleException:
CalledProcessErrorin line 335 of ~/Documents/_github_/pypsa-africa/Snakefile:
Command 'set -euo pipefail;  ~/opt/miniconda3/envs/pypsa-africa/bin/python3.9 ~/Documents/_github_/pypsa-africa/.snakemake/scripts/tmpr696eozw.build_renewable_profiles.py' returned non-zero exit status 1.
  File "~/Documents/_github_/pypsa-africa/Snakefile", line 335, in __rule_build_renewable_profiles
  File "~/opt/miniconda3/envs/pypsa-africa/lib/python3.9/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
WARNING:snakemake.logging:Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
ERROR:snakemake.logging:Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-08-13T160336.126840.snakemake.log
WARNING:snakemake.logging:Complete log: .snakemake/log/2022-08-13T160336.126840.snakemake.log
```

**Comment by pz-max** [comment]
Hi @ekatef, thanks for raising the issue :)
I am not the expert in our hydro implementation but reading the issue report I think we could clarify a bit. So you fixed the bug by adding a proj from Asia to the global dataset. Which projection was used? (EPSG:4326 ?) 

To me it is unclear what we should do to close this issue.
- You mention that we have an initial (hydrosheds) global dataset. But at the same time you mention that there are only macro-regions available. Could you clarify? Do we need to fix the data stored on Zenodo for the global case? 
- Regarding your questions if Asia might require hydrosheds from other continents... Probably yes. When optimizing Nigeria we also required upstream hydro information from neighbouring countries. So in particular for bordering countries errors might appear.

**Comment by ekatef** [comment]
Hi @pz-max, thank you for analysing this. Sorry for not a perfectly clear report :)

Yes, the CRS of the HydroBasins dataset is EPSG:4326 and that's defined in the `prj` file. I think this issue can be closed by supplementing a proj file for each of the hydrobasin shapefiles on Zenodo. Currently I was not able to extract the whole global dataset via https://www.hydrosheds.org/ but I may be missing something.

Regarding experiments with the regional datasets: thank you for sharing the experience with Nigeria modeling. My feeling is that with these transboundary watersheds issues we have one more argument towards the global approach :)

**Comment by pz-max** [comment]
@ekatef fair point. Seems we should discuss making the global data the default. Somehow, I have it available form my recent PyPSA-Africa run. But yes, the download transparency can be improved. I am adding this discussion here to the Thursday meeting so we can discuss and solve that together :)
![image](https://user-images.githubusercontent.com/61968949/184898246-4ece030e-df34-486e-ba0a-8e26a686bc10.png)

**Comment by ekatef** [comment]
@pz-max, absolutely agree that it'll be great to discuss the data workflow. Thank you for your support!

Probably, some additions to the docs would be helpful to facilitate a bit managing the data workflow (and prevent users from removing the key inputs... :) ). If you think it makes sense I'ld be happy to contribute.

**Comment by davide-f** [comment]
Sorry for the absense! I've been on holiday till today.

That's a weird issue: did you use the world hydrobasin shape?
The hydrobasins folder of the repo, in my case include not only the shp files but all the other auxiliaries.
![image](https://user-images.githubusercontent.com/67809479/184934075-2138e96f-f959-442f-a451-b50d89a43697.png)

I'd recommend to download the latest data package, I send you the link on discord.

**Comment by ekatef** [comment]
@davide-f, thank you so much for clarification! ( And I don't see any reason for apologies :) )

The issue was caused by using an outdated Zenodo data package. Then, I think we may safely close this.

**Comment by pz-max** [comment]
@davide-f would it make sense to specify the hybas output in the `bundle_config`? https://github.com/pypsa-meets-africa/pypsa-africa/blob/main/configs/bundle_config.yaml otherwise it might be hard to see wants coming out of the different bundle options.

**Comment by davide-f** [comment]
> @davide-f would it make sense to specify the hybas output in the `bundle_config`? https://github.com/pypsa-meets-africa/pypsa-africa/blob/main/configs/bundle_config.yaml otherwise it might be hard to see wants coming out of the different bundle options.

For clarity it is possible, in terms of workflow it does not change anything by why not :)
