### ISSUE TITLE
0 column and frequency is not properly cleaned in 'clean_osm_data.py'

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#469]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

I am extracting and cleaning the OSM data for the United States. However, this works not smoothly and requires fixes.

## Error Message 1 - 0 column
Executing this lines:
https://github.com/pypsa-meets-earth/pypsa-earth/blob/e35545c3bcfa14b6eef714f28d95ef807db450cb/scripts/clean_osm_data.py#L716
leads to the error message:
```bash
AttributeError: 'int' object has no attribute 'encode' 
```
 because `df_all_lines` has a 0 column. Using the US as test case, we should figure out where the 0 columns is created and remove the bug. Adding this line `df_all_lines.drop(labels=0, axis=1, inplace=True)` before the geojson can be used as temporary fix.

## Error Message 2 - frequency is not properly cleaned

This line:
https://github.com/pypsa-meets-earth/pypsa-earth/blob/e35545c3bcfa14b6eef714f28d95ef807db450cb/scripts/clean_osm_data.py#L80
Is raising the following error message:
```
Exception has occurred: ValueError
could not convert string to float: '60;60'
```
Analysing the `lines` by `lines.tag_frequency.unique()` shows quickly that the frequency is not properly cleaned: 
```bash
array([60.0, '60', '60;60', '0', '25', '60;0', '6', '50'], dtype=object)
```

**Comment by davide-f** [comment]
I think  PR #548 should solve this problem once finalized

**Comment by davide-f** [comment]
Solved by https://github.com/pypsa-meets-earth/pypsa-earth/pull/584
