### ISSUE TITLE
Need a test for tighter CO2 constraint

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#489]
See reason from Github conversation:

@MaxParzen The CI in pypsa-earth-sec is now failing and small changes in the base config file used for the test may be the reason. See https://github.com/pypsa-meets-earth/pypsa-earth-sec/actions/runs/3321595655/jobs/5489457714
No sol file is found, which sounds to me that the problem is infeasible.
Is the tutorial file exactly the same as the previous default test file?
What changes have been made for the main workflow? May be worth to verify that to understand why the CI is failing
GitHub [Merge pull request #153 from pypsa-meets-earth/fix_CI_github · pyps...](https://github.com/pypsa-meets-earth/pypsa-earth-sec/actions/runs/3321595655/jobs/5489457714)

MaxParzen — Today at 4:19 PM
The tutorial changed... I think the reason for the CI crash is the super tight CO2 constraint (0 CO2)?
https://github.com/pypsa-meets-earth/pypsa-earth/commit/68e2c74f842f61b017218020329ae135cb47747f#diff-549f6db36b21debe4d67dde1cf300ae74c28f15bb4be8368337c02272100fc13

**Ideally we should have two test:**
- 20% emission in Nigeria 
- No emission constraint in Nigeria

**Comment by davide-f** [comment]
I think we can close this issue.
Problems with such constraints are normal and the issue found by hazem has solved many problems we experienced

**Comment by pz-max** [comment]
Yeah happy to close. Let's see if this pops up again. In case it does, we just need to lower the values in the `test/custom.config.yaml`
https://github.com/pypsa-meets-earth/pypsa-earth/blob/ae284b21e1e01dbff97f223cbaad58651e5c44d4/config.tutorial.yaml#L121-L122
