### ISSUE TITLE
Installation.rst too bulky and needs changes

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#497]
Our installation.rst, https://pypsa-earth.readthedocs.io/en/latest/installation.html is too lengthy. **Our goal for the installation should be to get the user setup in 15-30min  such they are ready for the tutorial** -> other material is more learning material/ recommendation e.g. IDE choice which is helpful but should not be part of the installation procesure. Again, I find the [PyPSA-Eur instructions](https://pypsa-eur.readthedocs.io/en/latest/installation.html) much more compact and more suitable for 1st-time users. 

Compared to PyPSA-Eur, in our case:
-  The [Software requirements](https://pypsa-earth.readthedocs.io/en/latest/installation.html#software-requirements) are a list... I think we should more smoothly embedded this list within the steps. At the moment it is not clear if one should install everything.
- The Python3 point in the Software requirements is rather referring to training material
- IDE choice should be much shorter (one sentence) and only a recommendation.
- The **Note** at the end of the software requirements is irritating. As mentioned in issue https://github.com/pypsa-meets-earth/pypsa-earth/issues/496 we can probably remove it
- Section **Download_data** should be removed... It should not even be a part of the tutorial.rst. I suggest that we refer to the hackathon at the end of the tutorial.

### Suggestion:
- Let's start from the roots with a 1:1 equivalent to PyPSA-Eur
- Extend it by the **Java** installation note (otherwise the workflow would break for powerplantmatching)
- ... Add other small compact notes if needed

**Comment by ekatef** [comment]
I think the draft is ready.

It's a bit unusual to include a tutorial on third-parties software into documentation. However, our links to git tutorials or Snakemake explanations were very handy when introducing the model. And I'd rather add some bits to the `Software hints`... 

@pz-max, @AnasAlgarei , @davide-f, what do you think?
