### ISSUE TITLE
Isolated buses are kept after clustering

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#506]
https://github.com/pypsa-meets-earth/documentation/blob/d2ef4c870350bb6f6c0f5fa263e0140e20089af9/notebooks/tutorial_network_analysis.ipynb

The isolated buses shouldn't be there.
![image](https://user-images.githubusercontent.com/61968949/199314151-f507b528-e3d6-4d30-8181-9a4ebd812582.png)

**Comment by PeterKlein11** [comment]
Similar issue with isolated buses when running the model for South Africa
![image](https://user-images.githubusercontent.com/87762996/200599658-1600632f-eded-4072-af8d-f3a1c5ab0f49.png)
