### ISSUE TITLE
OSError raised on Windows 

### ISSUE THREAD

**Issue by vjha-gams** [pz-max/pypsa-africa#523]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

*Please provide a description of what the bug is and add a minimal example/command for reproducing the bug.*

While running the tutorial as explained in the github readme files, The command prompt always gives the following error message.
OSError: [WinError 1314] A required privilege is not held by the client. 

## Error Message

I have attached a screengrab of my windows terminal after it throws the error. I have also tried updating my symlink settings but up to no success.

![pypsaEarthError2](https://user-images.githubusercontent.com/104012009/202931002-12fbb638-97aa-407d-8747-4e4a1de136c8.png)

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```bash
<paste here>
```

**Comment by davide-f** [comment]
Hello, thanks for posting!
The problem unfortunately is know and it is related to the operating system.

If you run vscode as an administrator that problem shouldn't appear

**Comment by vjha-gams** [comment]
Earlier, I had tried running the same in command prompt with administrator access, but it did not work. Thus, decided to raise an issue. Thank you for the fix! It is working now.

**Comment by davide-f** [comment]
No problem, happy to have helped :)
