### ISSUE TITLE
Migrate from shapely 1.x to shapely 2.0

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#539]
## Describe the feature you'd like to see
Shapely upgraded to 2.0. There are a couple of breaking changes which raise errors.
To solve them, here is some migration code: https://shapely.readthedocs.io/en/stable/migration.html

One needs to install the `pypsa-earth` environment (from `environment.yaml`) without the current shapely version constraint e.g. `shapely` instead of `shapely<2.0` **and** then debug the code/ implement the migration code.

**Comment by davide-f** [comment]
Closed via #578
