### ISSUE TITLE
Taiwan demand data bug

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#556]
## Checklist
- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

I use "TA" (Taiwan) in the config.yaml (default).
Running `snakemake -j1 solve_all_networks` did not run because data was missing -> `ssp2-2.6/2030/era5_2013/Asia.nc`
Downloading the demand data manually solved it: https://zenodo.org/record/6569890#.Y7avu6fP1Qo

There may be some issues with the data interface:
- https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/scripts/retrieve_databundle_light.py
- https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/configs/bundle_config.yaml

**Comment by BartonChenTW** [comment]
hi @pz-max I have some of Taiwan's electricity demand data (hourly for a few years), but not sure if it could help.
p.s. I am very interested in building Taiwan's energy system.

**Comment by pz-max** [comment]
Hi @BartonChenTW, just tagged you on LinkedIn. Sure the hourly time-series would be great. We are currently only using a machine learning based prediction. We can 1. stream in your data & 2. Improve the machine learning method with your data. Do you have a link for the data? Or can you share it somewhere in case is genuinely open data?

**Comment by BartonChenTW** [comment]
Hi @pz-max, in principle, electricity generation data in Taiwan is open data - you can find it here: 
 - pass 3 months data, every 10 min https://data.gov.tw/dataset/37331 (sorry it is in Chinese but happy to help to translate)
 - live data, update very 10 min https://data.gov.tw/dataset/8931

However, the site is not easy to use (only Taiwan IP can download it), so I got a copy of data between 2017-2022 from a friend.
What is the best way to share those data? I am happy to tidy up the data and upload it to the online platform (zenodo?).

Also, I also tried to create a map about wind/PV generation in Taiwan. Happy to share that as well.

**Comment by pz-max** [comment]
@BartonChenTW yes, I think sharing the data on Zenodo and sharing a link here would help a lot. 
We get soon a new open-source package where especially the demand data in hourly or higher resolution over multiple years would be super helpful :)

It's also possible to use this "better" data in Taiwan, replacing the default data we use. It just needs an interface in PyPSA-Earth that needs to be built

**Comment by BartonChenTW** [comment]
No problem. I am new to Zenodo so might need some time to figure out how to use it. Will share the link as soon as I got it uploaded.

**Comment by BartonChenTW** [comment]
@pz-max Please find the link for Taiwan's electricity data on Zenodo here [here](https://zenodo.org/record/7537890#.Y8NTNHbLeCp). Feel free to let me know if you have any questions.
credit: Thanks to @PatrickFu0302 download and share the data!

**Comment by pz-max** [comment]
> @pz-max Please find the link for Taiwan's electricity data on Zenodo here [here](https://zenodo.org/record/7537890#.Y8NTNHbLeCp). Feel free to let me know if you have any questions. credit: Thanks to @PatrickFu0302 download and share the data!

Fantastic @BartonChenTW ! Do you also have .geojson or .shp (shapefiles) for the four areas?
Then the data would become most helpful for anybody

**Comment by BartonChenTW** [comment]
> Fantastic @BartonChenTW ! Do you also have .geojson or .shp (shapefiles) for the four areas? Then the data would become most helpful for anybody

@pz-max I don't have it now but happy to create one. I found a webpage https://geojson.io/, should I just use it to mark the area (polygon) of that fours areas in Taiwan? It will be easier if I can have some references or examples...

**Comment by pz-max** [comment]
Fantastic @BartonChenTW, yes drawing the four zones approximately would be sufficient. Here is an example of a file called `gadm_shapes.geojson`: ![image](https://user-images.githubusercontent.com/61968949/212775775-0bb05992-9d86-436f-ac3e-cda88af03b18.png)

The plain text of such an object looks like:
{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "GADM_ID": "NGA.1_1", "country": "NG", "pop": 3992493.75, "gdp": 35187179520.0 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 7.462831975000029,... ] ] ] } },
{ "type": "Feature", "properties": { "GADM_ID": "NGA.2_1", "country": "NG", "pop": 4448888.5, "gdp": 15398638592.0 }, "geometry": { "type": "Polygon", "coordinates": ...
...

**Comment by BartonChenTW** [comment]
@pz-max  I have found some existing geojson data for Taiwan and converted it to English with 4 areas defined by Taipower. Here is the [link](https://github.com/BartonChenTW/Taiwan_energy_system_analysis/blob/main/data/geojson/TaiwanArea.geojson). Feel free to let me know if you need anything else. I have the locations and power capacity of wind/solar in Taiwan as well. Happy to share it if it helps.

**Comment by pz-max** [comment]
@BartonChenTW , somehow I cannot access the link? Ideally, you post the geojson link in [pydemand](https://github.com/pypsa-meets-earth/pydemand/issues/2). Feel free to also share the wind and solar location and capacity for Taiwan. For this purpose, I would recommend opening a separate "Discussion" on GitHub summarizing all the data for Taiwan (with links). So when someone wants to model Taiwan we just check out the discussion topic.

**Comment by BartonChenTW** [comment]
@pz-max sorry that I forgot to set the GitHub repository to public - the [link](https://github.com/BartonChenTW/Taiwan_energy_system_analysis/blob/main/data/geojson/TaiwanArea.geojson) should work now. Not sure where is the best place to share the data, but now I tend to upload small files in GitHub and large files in Zenodo. Any suggestions for better platform will be appreciated. Also, will post the link under pydemand and create a discussion shortly.
