### ISSUE TITLE
TopologyException in build_bus_regions for India

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#583]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

This new error is appeared. Do we need the unary_union? @ekatef do you remember why it was needed?
Fixes may include make_valid or buffer(0); see [link](https://stackoverflow.com/questions/74779301/unable-to-assign-free-hole-to-a-shell-error-when-flattening-polygons)

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```bash
This is the repository path:  /data/davidef/git_world/pypsa-earth
Had to go 0 folder(s) up.
INFO:pypsa.io:Imported network base.nc has buses, lines, links, transformers
Traceback (most recent call last):
  File "/data/davidef/git_world/pypsa-earth/.snakemake/scripts/tmp97rr4m99.build_bus_regions.py", line 217, in <module>
    onshore_geometry = custom_voronoi_partition_pts(
  File "/data/davidef/git_world/pypsa-earth/.snakemake/scripts/tmp97rr4m99.build_bus_regions.py", line 83, in custom_voronoi_partition_pts
    outline = unary_union(outline)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/shapely/ops.py", line 137, in unary_union
    return shapely.union_all(geoms, axis=None)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/shapely/decorators.py", line 77, in wrapped
    return func(*args, **kwargs)
  File "/home/davidef/miniconda3/envs/pypsa-earth/lib/python3.8/site-packages/shapely/set_operations.py", line 426, in union_all
    return lib.unary_union(collections, **kwargs)
shapely.errors.GEOSException: TopologyException: unable to assign free hole to a shell at 88.285928250999973 24.888026479000189
```

**Comment by ekatef** [comment]
@davide-f, as I remember there were two reasons for applying `unary_union()` before making Voronoi partition:

1) as a situative fix for Kazakhstan when it suddenly appeared that some shapes consist of several polygons;

2) as an [interim solution](https://github.com/pypsa-meets-earth/pypsa-earth/pull/532#issuecomment-1345399966) when addressing the geometry issue.

However, I'm not able to reproduce the first point at the time being while the second one has been addressed in the final version of the geometry fix. Could we probably just remove/comment out this `unary_union()` in `build_bus_regions`?

What I do not quite understand is why this enclave issue was not resolved by using `make_valid` or `buffer` applied when building the shapes...

**Comment by davide-f** [comment]
Closed by https://github.com/pypsa-meets-earth/pypsa-earth/pull/572
