### ISSUE TITLE
Create a notebook-like in package documentation to support data validation

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#587]
## Describe the feature you'd like to see

Data validation is critical and using the output statistics by PR #579 and some global database on installed capacity by IEA or other sources it is possible to perform preliminary data validation.
This task aims to develop such notebook that:
- takes as input the files from folders "results/{scenarios}/stats.csv" (see PR #579)
- loads open data on power systems across the world
- Creates plots to perform the validation

Plots and tables shall have different aggregation levels.

**Comment by davide-f** [comment]
Hey @energyLS :)
Could you update on the status? It may be good for example to state here sources that you found and alike to do the comparison.
The deadline is in a month and we would need to start investigating. It is not urgent but starting to have some ideas may be good

**Comment by energyLS** [comment]
Hey @davide-f sure. I am starting today, I have just set up a draft PR: https://github.com/pypsa-meets-earth/documentation/pull/48
Will continue later this afternoon :)
