### ISSUE TITLE
Build_hydro issues

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#588]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

By running the model for RU some GDAL warning appears and in the end the time series for hydro miss a bus.
Needs some checks

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```bash
Traceback (most recent call last):
  File "/data/davidef/git_world/pypsa-earth/.snakemake/scripts/tmpm42qah_l.add_electricity.py", line 890, in <module>
    attach_hydro(n, costs, ppl)
  File "/data/davidef/git_world/pypsa-earth/.snakemake/scripts/tmpm42qah_l.add_electricity.py", line 540, in attach_hydro
    assert missing_c.empty, (
AssertionError: 'resources/RU/renewable_profiles/profile_hydro.nc' is missing inflow time-series for at least one bus: 13085
```

**Comment by ekatef** [comment]
Do you mean GDAL warnings like `GDAL signalled an error: err_no=1, msg='Too many points (529 of 529) failed to transform, unable to compute output bounds'`?

I have experimented with them a bit trying to use different cutout files, and it didn't resulted in any change the GDAL warnings. So, the warnings look rather like an issue which relates to shapes. 

Regarding hydro part of the renewable profiles, it works but solar and wind parts just get stuck on availability calculations (probably due to some memory issues).

**Comment by davide-f** [comment]
Also for US the same issue appears.
It seems that the hydro procedure does not produce some time series for some buses.

We also have plenty of those warnings, though I am unsure whether they are correlated to this problem.

**Comment by davide-f** [comment]
This PR may be closed with #631; tested for US.
This issue was generated by the fact that some nodes are not contained in any hydrobasin that led to this problem
However, this problem of buses not falling into any hydrobasin is a bid weird and may be better crosschecked. So I'd leave this issue open

**Comment by davide-f** [comment]
In us some of the dropped buses where plants in hawai where maybe hydrobasin was not available.
I am prone to close this issue.

**Comment by ekatef** [comment]
Another reason why there can be troubles with locating bus is a hydrobasin is complicated landscape when the boundary between the sea and the rivers may be not obvious + probably, bus coordinates not perfectly accurate:

<img width="533" alt="image" src="https://user-images.githubusercontent.com/30229437/225903250-bda72071-d970-491d-bde4-2256d9a3ebd6.png">

Don't think it's very important as such landscapes are anyway not particularly suitable to place hydro power

**Comment by davide-f** [comment]
Indeed, as a comment, there are different types of hydrobasins, with and without lakes.
It should be nice to investigate their effect.
I'll add an issue

**Comment by ekatef** [comment]
Ah, sorry, "sea" is a bit misleading. It was meant as a part of the ocean, not the lake :)
Thanks for the issue!
