### ISSUE TITLE
Update simplify network along PyPSA-Eur dev

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#592]
## Describe the feature you'd like to see
Let's update simplify_network.py to PyPSA-Eur standard. Some functions are totally missing such as `aggregate_to_substations` and features such as hierarchical clustering: https://github.com/pypsa-meets-earth/pypsa-earth/issues/404

The update might also help solve bugs such: https://github.com/pypsa-meets-earth/pypsa-earth/issues/586

**Comment by davide-f** [comment]
I think this issue should include also the revision of cluster_network.
simplify and cluster scripts have been updated and needs to be revise cojointly.
