### ISSUE TITLE
Make repository REUSE compliant

### ISSUE THREAD

**Issue by euronion** [pz-max/pypsa-africa#599]
TBD around March 2023. Maybe after decision on re-licencing was made.

**Comment by davide-f** [comment]
Thanks @euronion for the issue.
Would you mind adding some description of the issue in case someone may be interested in addressing this issue?

Thank you :)

**Comment by pz-max** [comment]
Just found some time to explain. The task is to make the tool REUSE compliant and add a badge (see [PyPSA-Eur](https://github.com/PyPSA/pypsa-eur)). The process to make PyPSA-Earth REUSE compliant is relatively simple. There is a perfect [guide](https://reuse.software/) to do that and it might take only a couple of hours. The person doing it needs create a Pull Request.

**Comment by ekatef** [comment]
Coping comments from our discussion with @pz-max on that topic:

If I understand REUSE tutorial https://reuse.software/tutorial/ properly, we need to make sure that:

1) each file (including .gitignore) contains a license and a copyright headers;

2) each image should be complemented with both license and copyright files.

Reuse checker https://github.com/fsfe/reuse-tool can be applied to ensure that nothing was missed and eventually introduce some fixes

Actually, our script files still contain both headers. But indeed an automated check is a very good idea as the whole licensing design seems to be not quite straightforward. E.g. our  `.gitignore` might definitely need some fixes from this perspective

`reuse` tool is hery helpful to provide such fixes automatically

**Comment by pz-max** [comment]
Just a comment on @ekatef , some of the existing headers need to be fixed.
So probably realistic to complete consider disregarding the old ones

**Comment by ekatef** [comment]
> Just a comment on @ekatef , some of the existing headers need to be fixed. So probably realistic to complete consider disregarding the old ones

Thanks a lot @pz-max!
I'd say the first step is to get reuse work locally and obtain the results of REUSE checking. Which still will be a very good achievement :)

**Comment by ekatef** [comment]
Initial results of REUSE checking (credits to @juli-a-ko)
```
# SUMMARY
 
* Bad licenses:
* Deprecated licenses:
* Licenses without file extension:
* Missing licenses: CC-BY-4.0, CC0-1.0, GPL-3.0-or-later, MIT
* Unused licenses:
* Used licenses: CC-BY-4.0, CC0-1.0, GPL-3.0-or-later, MIT
* Read errors: 0
* Files with copyright information: 88 / 133
* Files with license information: 86 / 133
 
Unfortunately, your project is not compliant with version 3.0 of the REUSE Speci
fication :-(
```

What I do not completely understand is why the checker is not happy with "GPL-3.0-or-later".  We do have it [attached](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/LICENSE) to the project...

**Comment by ekatef** [comment]
Update: some further investigation has shown that a likely reason of the mentioned `reuse`-license complains is caused by a requirement to have a name of the license file corresponding to the license name. Thanks JuliaK for the update

Working to fix it
