### ISSUE TITLE
Type Casting error

### ISSUE THREAD

**Issue by energyLS** [pz-max/pypsa-africa#605]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

In `build_osm_network.py` line 817 the typecasting `.astype(buses.dtypes.to_dict()` throws an error. Reason: this line tries to convert `NAN` from `"station_id": [np.nan] * length` to Int64, which is not possible.

This error only appears for countries without data.

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

**Comment by pz-max** [comment]
Hi @energyLS , thanks for reporting.
How to reproduce the error? (config?)
Is it possible to remove the `np.nan`?

**Comment by energyLS** [comment]
Hi @pz-max sorry for unclear description. You can reproduce the error when setting:
`countries: ["Africa"]`

Well, the `np.nan` is introduced on purpose a view lines above the error:
https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/scripts/build_osm_network.py#L805

The error then appears here:
https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/scripts/build_osm_network.py#L818

The solution I proposed in #606 works, but if there is any other idea I am happy to implement it. But to me, it doesn't look bad.

**Comment by davide-f** [comment]
Hello!
Interesting bug; we never experienced it. As a comment, are you using the latest repo and environment? [may be worth checking in a parallel git folder and another environment without replacing the existing you are using]

Few comments:
- the np.nan was just a preliminary initialization; the code later on is expected to replace every entry of the column with an integer. If that does not work and a np.nan remains, the bug lays in where that does not happen and this is a side effect
- if this problem arises before the workflow replace the values, then simply changing the [np.nan] with [-1] may work. However, I am concerned about the first point as something hidden may not work.
- the simplest explanation may be that a combination of old/new environment/repo is leading to that phenomenon

In the country-wise optimization, I've not experienced this error for the time being, but I haven't tested Africa yet

**Comment by pz-max** [comment]
Closing because of https://github.com/pypsa-meets-earth/pypsa-earth/pull/606#issuecomment-1461881590
Let us know if the error appears again such that we can add fixes.
