### ISSUE TITLE
Add notebook and documentation for `make_statistics`

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#608]
GOAL: add a notebook and documenation for `make_statistics`.
From the following discussion:

@davide-f Do you think we could create a small notebook in the [`documentation`](https://github.com/pypsa-meets-earth/documentation/issues/46) repo to demonstrate the `make_statistic` stuff?

I am thinking about a super small notebook:
- instructions how to modify the config tutorial/ test case for Nigeria
- instructions what command to use to run the whole stats stuff
- some tables with the stats maybe with little explanations

This would also help review a lot

_Originally posted by @pz-max in https://github.com/pypsa-meets-earth/pypsa-earth/issues/579#issuecomment-1429407970_

**Comment by Aathirajan** [comment]
Can anyone assign me this issue?. I'm new to open source..

**Comment by pz-max** [comment]
@Aathirajan , sure added you :) @davide-f  will soon share a preliminary notebook that can help.
Starting point before addressing the issue would be to run the PyPSA-Earth tutorial

**Comment by davide-f** [comment]
Hello @Aathirajan cool to have you onboard for this task! :)

To work on it, you may:
1. start by running the PyPSA-Earth tutorial to get familiar with it as [discussed here](https://pypsa-earth.readthedocs.io/en/latest/short_tutorial.html)
2. Once the execution has been successful, please run `snakemake -j 1 make_statistics` on bash (if unix-based) or prompt (if windows)
3. That command will create the file "results/stats.csv" into the results folder, that is needed to crete the desired notebook.
4. The new notebook shall be placed into the documentation folder available at [this link](https://github.com/pypsa-meets-earth/documentation). At the link there are instructions on how to install the documentation as well.
5. Then, in your local repository, you can create a new notebook called "make_statistics.ipynb" into the folder "notebooks" to explore the data contained into stats.csv

**Comment by Aathirajan** [comment]
Yeah! @pz-max @davide-f  Thanks for having me. I'll look into it. 
To ask my doubts,Is there discord/slack channel to join?

**Comment by pz-max** [comment]
> Yeah! @pz-max @davide-f Thanks for having me. I'll look into it. To ask my doubts,Is there discord/slack channel to join?

https://discord.gg/AnuJBk23FU @Aathirajan

**Comment by Aathirajan** [comment]
@pz-max thanks!

**Comment by davide-f** [comment]
Hello @Aathirajan
Let us know and comment here if you need something :)
What's the status on this issue?

**Comment by Aathirajan** [comment]
As a beginner, i just feel overwhelmed.

**Comment by Aathirajan** [comment]
Can you give me sometime, like 5 days?
