### ISSUE TITLE
Update on documentation - configuration section

### ISSUE THREAD

**Issue by asv365** [pz-max/pypsa-africa#609]
Increased specifications and typo fixes in the documentation. The proposed changes in the documentation are:

1.	Specify a limit on snapshots/start and snapshots/end. Is 2023_01_01 a good upper bound? Is there a lower bound?

2.	There is no section in the documentation for load_options. There, we can specify that the load_options/weather_year has to be within the snapshot range. On load_options/prediction_year are 2030, 2040, 2050, and 2100 the only options for now?
 
3.	The picture in the lines section includes too many things, the “lines” only appear at the very end. Replace this.

4.	Create subsections in the electricity section, as in the renewables section.

5.	The section load from the documentation doesn’t seem to refer to anything on the config file. Shall we remove this?

**Comment by ekatef** [comment]
Hello @asv365! Thanks a lot for your feedback. That is very helpful to improve the model usability.

Let's go point by point:

1. The snapshot should correspond to the timeframe for which cutout has been built.
2. Good point! The available `weather_year` and `prediction_year` values can be checked by looking into `pypsa-earth/data/ssp2-2.6` folder. Currently there are demand data for 2011, 2013, 2018 weather years and for 2030, 2040, 2050, and 2100 scenario prediction years

I think we may include some explanations on points 1 and 2 into an ongoing PR #603. Many thanks for your suggestions!

Regarding 3-5, absolutely agree that the section structure could be more clear. I'd also say that it would be helpful to supplement each subsection with a short description like it's done for `run`. However, such a revision should keep in sight the whole structure `Configuration` section and be consistent with the configuration files. If you want to work on this we would be happy to support you :)

**Comment by asv365** [comment]
Thanks for your feedback, @ekatef! Shall I write a comment on PR #603 about points 1. and 2.?

Regarding point 1., is there a limit on the years for which the cutouts can be built?

I will start working on points 3-5 soon, creating a pull request once it is ready. Agreed on the short description like it's done for `run`.

**Comment by ekatef** [comment]
> Thanks for your feedback, @ekatef! Shall I write a comment on PR #603 about points 1. and 2.?
> 
> Regarding point 1., is there a limit on the years for which the cutouts can be built?
> 
> I will start working on points 3-5 soon, creating a pull request once it is ready. Agreed on the short description like it's done for `run`.

Thanks, I have linked #603 with our discussion here :)

Regarding years used to build a cutout, it depends on ERA5 data availability. [ERA5 page](https://www.ecmwf.int/en/forecasts/datasets/reanalysis-datasets/era5) states that it's available from 1950 and updated continuously with about 3 month delay. They also ask to treat data on 1950-1978 as preliminary (as that is a rather recent development). 

Thank you for raising the issue here and looking forward for you PR. You might want to create [a draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) first which can be transformed into a regular PR once ready. Usually we use draft PRs as an opportunity to discuss work in progress :)

**Comment by asv365** [comment]
Points 3, 4, and 5 are being addressed in PR #612.

**Comment by ekatef** [comment]
> Points 3, 4, and 5 are being addressed in PR #612 

@asv365 Super :) Thanks a lot for taking it!
