### ISSUE TITLE
Create continent-wise default cutouts for continents beyond Africa

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#623]
## Describe the feature you'd like to see

New users joining have problems getting started when they are interested in regions beyond Africa as the cutout must be created from scratch.
For African countries, we do have the African template cutout that is already available in the databundles but no other region is covered.
It could be nice for someone to create other cutouts for other regions.
Examples may be:
- Asia (eventually divided into blocks as it is large)
- Middle East
- SouthAmerica
- Oceania
- Europe
- NorthAmerica

To do the above, there is the need to follow the procedure in [our documentation](https://pypsa-earth.readthedocs.io/en/latest/tutorial.html#build-the-custom-cutout):
In particular:
1. Register to the Copernicus service [as described in our documentation](https://pypsa-earth.readthedocs.io/en/latest/tutorial.html#build-the-custom-cutout)
2. copy the `config.default.yaml` file and rename it as `config.yaml`
3. change the value in "countries" to match the name of the region under consideration, e.g. countries: ["Asia"], ["SouthAmerica"], ...
4. execute the workflow for the target list of country
5. use the file `scripts/zipfolders_googledrive` to zip the file using the function `zipFilesInDir("./cutouts", "cutouts.zip", lambda x: True, include_parent=False)`
6. upload the file `cutouts.zip` to google drive and write to us, so that we can help you avoid filling your available space in your google drive
7. Modify the file `configs/bundle_config.yaml` to add a new databundle for the region under consideration, following the template of the entry `bundle_cutouts_africa`
8. Create the PR with the change

**Comment by Tomkourou** [comment]
Working on South East Asia right now. Happy to be assigned.

**Comment by Emre-Yorat89** [comment]
I am happy to generate cutouts for western asia countries. It is abbreviated as countries = ["WAS"].
