### ISSUE TITLE
Modeling CN needs some testing and improvements

### ISSUE THREAD

**Issue by ekatef** [pz-max/pypsa-africa#629]
Modeling China means implies a high level of complexity and requires addressing some known problems. This issue aims putting it all together. In particular, we need to:

1. Check if the results of data extraction are appropriate. The current picture looks like follows:

### base.nc

<img width="812" alt="image" src="https://user-images.githubusercontent.com/30229437/224503061-e97df642-9673-4f81-ab07-d660f45009c5.png">

### elec_s.nc

<img width="795" alt="image" src="https://user-images.githubusercontent.com/30229437/224503086-d4a29c33-4d8a-4585-b2a8-aee9658b25f4.png">

Note: the pictures above do not yet include improvements provided by #620. Re-calculating on the updated `clean_osm_data` shall eliminate loss of some lines currently obvious from comparison the base and simplified networks.

2. A simplification procedure should be revised to 
    * resolve an issue #586 due to misinterpretation of links
    * represent DC lines in a more proper way (see #621 for details)

3. Examine and validate topology of the final model to ensure that the workflow is working properly

**Comment by davide-f** [comment]
Hello @ekatef :)
This Issue can be closed now, right?

**Comment by ekatef** [comment]
Hello @davide-f :)

We have fixed point 2 from the list.

As for the results for topology,  an output of recent testing looks like follows:

# base.nc

<img width="799" alt="image" src="https://github.com/pypsa-meets-earth/pypsa-earth/assets/30229437/6b9d6b1e-6837-440e-8bd2-451c327da064">

# elec_s.nc

<img width="779" alt="image" src="https://github.com/pypsa-meets-earth/pypsa-earth/assets/30229437/bde0b0c1-4bf5-411a-89ab-403300cf3017">

So, network is more complete now. There may be some issue by clustering, as some combination of clustering parameters can give rather weird results. But that is another story, I think. This issue can be definitely closed :)
