### ISSUE TITLE
Custom_powerplant not working properly

### ISSUE THREAD

**Issue by carlosfv92** [pz-max/pypsa-africa#655]
## Checklist

- [ ] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [ ] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

*Hi everyone, I'm trying to use the custom_powerplants functionality so the built_powerplants can make use of a country-specific database to run a simulation. I've set up the custom_powerplant.csv file as suggested in the comments at the beginning of the script and found that there are problems with the suggested format.
It seems that after the predefined data is used to create the ppl dataframe (line 269), the script automatically changes the country name to its corresponding alpha2 code. After this, the custom_powerplants are added, and because the renaming process was done before this, they keep using the same country name instead of the alpha2 configuration. Because of this, when buses are assigned to the index of powerplants (line 290), the process doesn't include the newly added powerplants. 
I tried using the helpers to change the format of the custom_powerplant file but couldn't manage to run everything properly so I made the changes manually for the names in the country column. After this, the country-specific powerplants were recognized in the ppl dataframe. 
However, I'm finding similar "tagging" conflicts with the format used for the "carrier/fueltype" column for natural gas, biomass, pv and onwind technologies. While these have been solved (changing "natural gas" to "OCGT" or "CCGT" for example, I'm still having a problem with hydro powerplants not being included in the model. I'm trying to figure out how hydro powerplants should be named in each column (and if there are some additional columns or inputs I shouldn't consider checking) so they can be recognized and added to the output file (powerplants.csv)... Any comments are welcome

(I'm using the version of the repository from 16/02/23)

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```bash
<paste here>
```

**Comment by ekatef** [comment]
Hey @carlosfv92, thanks a lot for a detailed description. That is really very helpful as power plants data often need some refinement and updates.

Regarding hydropower plants, they have `Hydro` as `Fueltype` and `Reservoir` or `Run-Of-River` as `Technology` in the ppm output, for example :

```csv
,Name,Fueltype,Technology,Set,Country,Capacity,Efficiency,Duration,Volume_Mm3,DamHeight_m,StorageCapacity_MWh,DateIn,DateRetrofit,DateOut,lat,lon,EIC,projectID,bus
0,Altinkaya Turkey,Hydro,Reservoir,PP,TR,691.0828025477707,,,0.0,0.0,0.0,1988.0,1988.0,2088.0,41.3642,35.7259,"{nan, nan, nan, nan}","{'GEO': {'GEO-43086'}, 'GPD': {'WRI1018914'}}",5321
1,Birecik Turkey,Hydro,Run-Of-River,PP,TR,496.8877639579009,,,0.0,0.0,0.0,2000.0,2000.0,2100.0,37.05333,37.89,"{nan, nan, nan, nan, nan, nan}","{'GEO': {'GEO-42978'}, 'GPD': {'WRI1018921'}}",2928

```

Could you please check if it would work when using such format? Would be happy to do a more detailed investigation if needed

**Comment by carlosfv92** [comment]
Hi @ekatef! I was using that format but think I just found the problem... It seems that the model wasn't actually recognizing hydro powerplants with the "Reservoir" tag as powerplants due to the designation 'StorageUnit' in the add_electricity rule (line 513). 
What I did, so they can be recognized as powerplants, is change the designation from 'StorageUnit' to 'Generator', which seems to do the trick. Does that make any sense or am I messing with the storage characteristics/capabilities of the hydro powerplants by doing this?

**Comment by ekatef** [comment]
Hi @carlosfv92! I think it might be alright to define hydropower as `Generators` for debug purposes. Not sure however if you will obtain meaningful simulaiton results under such formulation, especially in case hydro power plays a significant role in the power system.

Are you able to check if the reservoir plants were added as `StorageUnit`? You can check available storage units with `n.storage_units`

**Comment by carlosfv92** [comment]
Hi @ekatef, since we talked at the pypsa-earth meeting I wasn't sure if I should continue the tread here, but just as a comment, I didn't find the hydro units (Reservoir) as StorageUnit (n.storage_units) either... I'm currently trying to update my version of PyPSA-Earth and reproduce all the changes I made so far... if something changes with the hydro in the new version I'll let you know here

**Comment by ekatef** [comment]
Hi @carlosfv92, don't worry that is perfectly fine to continue here discussion :) Actually, when discussing an issue during the meeting, it works very good to add after a brief description of what has been agreed.

Incorporation of reservoir hydropower is an interesting and very useful task. I'll be happy to support you in tackling it. Updating your repo is indeed a necessary first step as there were some recent updates related to hydro part

PS Thanks for your PR regarding custom powerplants format! :) My feeling is that it'll be very helpful.

**Comment by carlosfv92** [comment]
Hi @ekatef ! Some updates on this subject (hydro units): after struggling a little bit with the updated repo due to problems with the downloading of information (which I had to do manually since I think there were always some files missing) I finally run my scenarios again and now I am able to find the hydro reservoirs as storage units in the model (n.storage_units), which were missing before... However, while generators are assigned to buses in the clustering process (I'm currently working with a 4-node configuration), the storage_units are not being clustered (they keep the initial buses assigned in the add_electricity rule).
Any ideas on why this is happening? 
Also... should I change the name of this issue since now it became more specific?

![Capture](https://user-images.githubusercontent.com/103258059/233012607-40a16b12-fa30-426a-a9c6-48f35d633262.PNG)

**Comment by ekatef** [comment]
Hey @carlosfv92! Great that you are moving forward and thanks a lot for the update. It sounds really interesting.

No worries regarding the issue name. My feeling is that the title is clear enough. But indeed feel free to revise in case you would like to :)

Regarding clustering procedure, it sounds like there is an issue and some debugging is needed to resolve it. A couple of clarification questions:
1) Could you please plot a network before and after clustering? 
2) Aren't these non-clustered hydro storages attached to the isolated buses?

**Comment by carlosfv92** [comment]
Dear @ekatef after some debugging I found the problem mentioned before, however, while now hydro reservoir units are recognized as StorageUnits and assigned to the clustered buses, the model doesn't seem to be using them... attached you'll find some referential pictures:

Network before clustering: 
![image](https://user-images.githubusercontent.com/103258059/233931213-b4543280-3511-4304-9e81-577677f53f2d.png)

Network after clustering:
![image](https://user-images.githubusercontent.com/103258059/233931349-a62de029-a232-4d5b-85e9-2d6b915a2f53.png)

Storage units recognized in the clustered nodes (n.storage_units) - only some of them are linked to isolated systems:
![image](https://user-images.githubusercontent.com/103258059/233931558-c8cd0bda-fa85-42d9-821b-7c977525364a.png)

Empty dataframes of the units in time (n.storage_units_t):
![image](https://user-images.githubusercontent.com/103258059/233931971-ad058036-d5b9-4ae9-b9a1-dea0fb7199c5.png)

**Comment by ekatef** [comment]
@carlosfv92 thanks a lot for the detailed explanations! Sorry for the delay
A quick clarification question: is `n.storage_units_t` still a result of optimization?

**Comment by ekatef** [comment]
@carlosfv92, thanks a lot for the detailed discussion on this topic

It looks like reservoir hydropower plants are working in your model as base load generators. My feeling is that there is actually nothing wrong about it. So, congratulations with making custom power plants to work!

Agree that meaning of `hydro_max_hours` can be explained better in documentation. Feel free to suggest improvements.

I think a good place to start with advanced run-of-river implementation is looking into [build_renewable_profiles](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/scripts/build_renewable_profiles.py) script and [rescale_hydro()](https://github.com/pypsa-meets-earth/pypsa-earth/blob/bf3cbead03f9f95079e0ad09df1dbab85ce66112/scripts/build_renewable_profiles.py#L312) function in particular. @davide-f can give the most qualified comments on the general concept and particular implementation details

**Comment by carlosfv92** [comment]
@ekatef Thanks so much for the patience and comments! I'll keep working on this and see how far I can push the model and compare it to data from the TSO... however, improving the hydro calculation should be something to be tackled eventually and would gladly hear some ideas from @davide-f on how to start the process!

**Comment by davide-f** [comment]
@carlosfv92 can we close this issue? :)

**Comment by carlosfv92** [comment]
Hey @davide-f! yep, this one is done!
