### ISSUE TITLE
Add ImportError to build_powerplants.py for missing openjdk package.

### ISSUE THREAD

**Issue by Tomkourou** [pz-max/pypsa-africa#678]
## Describe the feature you'd like to see

The `build_powerplants` rule requires the openjdk package to work. However, if it is missing in the environment, the exception thrown does not make this clear. I would propose we add an [ImportError](https://docs.python.org/3/library/exceptions.html#ImportError) making this clear. The error arises here:

https://github.com/pypsa-meets-earth/pypsa-earth/blob/6a8871dafcc844703123377520669578999b86f1/scripts/build_powerplants.py#L298-L299

Or would it be better placed directly inside powerplantmatching?

**Comment by ekatef** [comment]
@Tomkourou, thanks a lot for the issue. My feeling is that it would be very helpful to have a meaningful error message instead of enigmatic mentioning of `linkfile.txt`

I think placing the issue here is perfectly alright, as it appears regularly on fresh pypsa-earth environments. Regarding where to introduce a fix for that, it could make sense to ask @davide-f for an advice, as Davide has been working with `powerplantmatching` a lot recently

**Comment by davide-f** [comment]
Hello :)
Indeed that is really useful!

My feeling is that we could create a specific function that is called at the beginning of the main in powerplantmatching where that function contains a try-catch block to capture exactly when this behavior fails.

As a remark this is a hidden problem of powerplantmatching and an issue is already opened there.
The nice fix would be to fix it there but the fix itself depends on the operating system as well.

**Comment by pz-max** [comment]
@Tomkourou just checking your PR. If I understood @davide-f correctly, I think what you propose would be better suited in powerplantmatching itself. But maybe its good in PyPSA-Earth anyways. I just checked if `java --version` also works on my Ubuntu laptop and it seems to work :+1:

**Comment by Tomkourou** [comment]
Happy to add it directly to powerplantmatching if you think it's better there.

**Comment by pz-max** [comment]
Both options are fine to me. If it's in ppm, it would also help the PyPSA-Eur guys & others and can be easier maintained. Let'se see what Davide says, but a great addition anyways :)
