### ISSUE TITLE
add rule run_tests to CI testing

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#715]
## Describe the feature you'd like to see
We are currently testing with GitHub actions.
We have simple Continous Integreation (CI) tests for Windows and Mac,
and a much more compact test for **Linux**.

The Linux CI test is implemented [here](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/.github/workflows/ci-linux.yaml) and should use [`run_tests`](https://github.com/pypsa-meets-earth/pypsa-earth/blob/b0e4d46470c57e3b84d82344309a8bdf1985d146/Snakefile#L70C7-L93) as this will 1) reduce the code volume and 2) is applying the test suite we recommend for every PR. Like for code reviews, we will run locally `snakemake -j1 run_tests` to see if everything is ok.

**Comment by davide-f** [comment]
There are downsides in doing this as we discussed with the others; the new makefile implementation is more compact.
We can probably close this issue; feel free to reopen if deemed relevant
