### ISSUE TITLE
Missing steps towards country-wise spanning with default configuration

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#736]
## Describe the feature you'd like to see

I've recently completed a second country-wise spanning using default configuration and up to 5 clusters per country.
Not all UN countries have been successfully executed and those not running are:
`['CN', 'JP', 'PH', 'GB', 'NZ', 'LT']`

- CN, JP, GB, PH: are most likely to issues related to simplify links at https://github.com/pypsa-meets-earth/pypsa-earth/issues/703
- NZ: this problem is a bug when using atlite reported in https://github.com/PyPSA/atlite/issues/282
- LT: is a weird bug that may be related to clustering issues as highlighted in https://github.com/pypsa-meets-earth/pypsa-earth/issues/735

I'll be taking care of the NZ problem, the others are open for help :)

**Comment by davide-f** [comment]
The problem with PH is confirmed to be solved using xarray to v2023.1.
We may need to increase the minimum package version

**Comment by Tomkourou** [comment]
I am also currently testing VN and it's not running out of the box for me. Wondering what could be the problem. 

Edit: Just saw your reference to PH.

**Comment by Tomkourou** [comment]
Fixed VN by downgrading xarray and netcdf4 as suggested here -> https://github.com/pypsa-meets-earth/pypsa-earth/issues/669#issuecomment-1536693607

**Comment by davide-f** [comment]
Outdated issue, closing
