### ISSUE TITLE
Occurence of "non-found" as shape_id in a regions_onshore shapefile  for some countries

### ISSUE THREAD

**Issue by ekatef** [pz-max/pypsa-africa#772]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

It appears that some `shape_id` values in `regions_onshore.geojson` for IN look like `not found.*` instead referring to the country code. Most likely that is linked with processing of contended areas.

**Comment by davide-f** [comment]
This should be complete, there was a past PR about this. the "contested areas", can we close this?

**Comment by ekatef** [comment]
The PR has been opened after contested areas have been fixed. Though, I'm not sure anymore how to reproduce the issue. So, that is definitely a good idea to close it 🙂
