### ISSUE TITLE
Conventional Gas Generators get kicked out

### ISSUE THREAD

**Issue by energyLS** [pz-max/pypsa-africa#774]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

This bug relates to #754 where the fueltype was changed from "CCGT" / "OCGT" to "natural gas".
In `add_electricty`, powerplants with the fuel type "natural gas" get filtered as seen here:
https://github.com/pypsa-meets-earth/pypsa-earth/blob/072b401a6cf1a14e2311bfd5d15ccfc55195348c/scripts/add_electricity.py#L380-L381

## Possible solutions

- Add "natural gas" to the config here (downside: the carrier "natural gas" could not be pypsa-standard?): https://github.com/pypsa-meets-earth/pypsa-earth/blob/072b401a6cf1a14e2311bfd5d15ccfc55195348c/config.default.yaml#L149
- Convert "natural gas" to "CCGT" here (straightforward, but change to OCGT or CCGT?): https://github.com/PyPSA/pypsa-eur/blob/cfa99cb3276a14ed8d26acd54f7240af46cd6127/scripts/add_electricity.py#L210
- Or partly revert #754 to make sure "CCGT" or "OCGT" stay as `fueltype`, by modifiying https://github.com/pypsa-meets-earth/pypsa-earth/pull/754/files#diff-b9faae86c53d5ce6cc8f484a9db580194fd1b9c9190a3eca90cfc182df87de0fL263

@Tomkourou and @pz-max what do you think? I am happy to issue a PR.

**Comment by Tomkourou** [comment]
Hi @energyLS do we understand why pypsa-eur uses OCGT and CCGT as carriers? I would not typically refer to them as carriers but technologies. Is it to separate them in plotting functions? I would personally prefer to add natural gas as a fuel type.

**Comment by energyLS** [comment]
Hey @Tomkourou totally agree, pretty sure though thats how it is done throughout the models. I think changing it (as proposed in option 1) would involve a lot of work and less compatability with the other models, which we should avoid.

**Comment by energyLS** [comment]
@Tomkourou just a quick follow-up: do you have other ideas or should we get some inspiration from others?

**Comment by pz-max** [comment]
@energyLS , thanks for pushing this.
My feeling is:
- keep build_powerplants as it is. Because the correct fuel type for CCGT&OCGT is natural gas
- add modification in add_electricity before the filter and rename natural_gas carrier to CCGT & OCGT to follow the existing inconsistency of naming. In mid-term it might be good to remove this naming inconsistency by differentiating between carrier and technology name

What are your thoughts?

**Comment by energyLS** [comment]
@pz-max thanks for your ideas, I agree with your proposal. A very simple modification would be to add the line
`"natural gas": "CCGT",` here: https://github.com/PyPSA/pypsa-eur/blob/cfa99cb3276a14ed8d26acd54f7240af46cd6127/scripts/add_electricity.py#L210.
Downside: we don't have a distinction between CCGT and OCGT. So should we go for a slightly more sophisticated filter, taking the technology type into account as well?
Again, happy to do a PR either way :)

**Comment by pz-max** [comment]
Yep @energyLS doing the sophisticated filter might be good.
Having only CCGT is not an option. Looking forward to review your PR :+1:
