### ISSUE TITLE
generalise currency conversion

### ISSUE THREAD

**Issue by Tomkourou** [pz-max/pypsa-africa#777]
```
    ] # TODO generalise currency conversion 
```

https://github.com/Tomkourou/pypsa-earth/blob/e319f409108dc707892bf088e598f0c6a99c3327/scripts/add_electricity.py#L210

**Comment by pz-max** [comment]
Added a [currency converter](https://github.com/PyPSA/technology-data/blob/cb44e9f10e2d3394f380df0150ed748c453cc4a2/scripts/compile_cost_assumptions.py#L735-L751) recently in technology-data. Improving the architecture there might be useful. Not sure if it is necessary to do all the unit cleaning and correct currency converting in PyPSA-Earth again. If people provide new data we should ideally go over the technology-data route.

Closing this issue for now.
