### ISSUE TITLE
local variable 'dc_lengths' referenced before assignment

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#810]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

For "NL" the following error applies
The reason is the handling of _prepare_connection_costs_per_link that may require some refining to better handle dc lines as link or lines

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```bash
Traceback (most recent call last):
  File "/pypsa-earth/.snakemake/scripts/tmps282icbm.simplify_network.py", line 814, in <module>
    n, simplify_links_map = simplify_links(
  File "/pypsa-earth/.snakemake/scripts/tmps282icbm.simplify_network.py", line 368, in simplify_links
    connection_costs_per_link = _prepare_connection_costs_per_link(n, costs, config)
  File "/pypsa-earth/.snakemake/scripts/tmps282icbm.simplify_network.py", line 178, in _prepare_connection_costs_per_link
    dc_lengths
UnboundLocalError: local variable 'dc_lengths' referenced before assignment
```

**Comment by ekatef** [comment]
Thanks for the report! Sounds like the problem is cased by this fragment:

https://github.com/pypsa-meets-earth/pypsa-earth/blob/dbca213b43bf96fa25ec5b4785cddadec3a85f5c/scripts/simplify_network.py#L164-L169

Apparently, an additional check is needed when initialising `dc_lengths`...  (Sorry for that!)

**Comment by davide-f** [comment]
@ekatef np :) if you don't mind, I'll try to briefly address this bug in the world PR open to ease the world testing.
Yet the fix is not aimed to cover all the functionalities.

What I'd do is to implement the if/else using the config option, no more

**Comment by ekatef** [comment]
@davide-f of course feel absolutely free to fix it as you feel like! :)

**Comment by davide-f** [comment]
Closing as it has been solved
