### ISSUE TITLE
Do not remove a cutout file if still exists

### ISSUE THREAD

**Issue by ekatef** [pz-max/pypsa-africa#818]
Currently, running `build_cutout` rule removes an existing cutout without requesting any confirmation. That can lead to a situation when an existing cutout is lost just because of forgetting to put back `build_cutout: true`. That is, an easy-to-do user error can easily cause loss of some considerable amount of data.

Possible solutions:
1) do nothing if the requested cutout file still exists;
2) create a new file adding a prefix to a name;
3) trow a prompt asking for a confirmation.

The reason of this behaviour is Snakemake logic, which silently erases the rule outputs in case the rule should be executed. Workarounds exist even if they are not very elegant, e.g. https://groups.google.com/g/snakemake/c/bww8_E4YWlQ

**Comment by davide-f** [comment]
Thanks for the issue! :D

I'd be against 2.
A prompt for confirmation may be undesirable, unless no dependencies are required.

An option may be
If any cutout in the list of the cutouts (more may be present) already exists, then:
a. Do not enable the rule and through a warnign
b throw an error

Let's discuss over it tomorrow if we have time :)

**Comment by ekatef** [comment]
Closed as completed with #839
