### ISSUE TITLE
Running the 'all' wildcard in solve_network returns error, add a "min" wildcard to select the minimum number of clusters 

### ISSUE THREAD

**Issue by Tomkourou** [pz-max/pypsa-africa#819]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

*Please provide a description of what the bug is and add a minimal example/command for reproducing the bug.*

As discussed, using the `all` wildcard when clustering the network does work well. However doing the same when trying to solve the networks returns the following error

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```bash
ERROR:snakemake.logging:InputFunctionException in rule solve_network in file /home/adminuser/toms_test/pypsa-earth/Snakefile, line 677:
Error:
  ValueError: invalid literal for int() with base 10: 'all'
Wildcards:
  simpl=
  clusters=all
  ll=copt
  opts=1H
Traceback:
  File "/home/adminuser/toms_test/pypsa-earth/Snakefile", line 672, in memory
```

Need's further investigation as it might be an easy fix and it's a useful wildcard. I also had a quick peruse of the documentation and could not find it there. I think it's worth documenting.

**Comment by davide-f** [comment]
Nice check @Tomkourou !
Could you share the scenario configuration you used?

**Comment by davide-f** [comment]
By checking the code, I'd expect the scenario to have `clusters=["all"]`

**Comment by Tomkourou** [comment]
> By checking the code, I'd expect the scenario to have `clusters=["all"]`

Good point, there may have been an int in my config. Let me run it again with `clusters=["all"]` and come back.

**Comment by Tomkourou** [comment]
Defining `clusters=["all"]` and then running the same snakemake command returns the same error as before.

**Comment by davide-f** [comment]
Nice catch!
The fix should be easy, there is the need to add an elif in memory function to solve the problem, similarly to [how it was done in pypsa-eur](https://github.com/PyPSA/pypsa-eur/blob/e34cec427b38779ca49350d55bf98a60ed586ca1/rules/common.smk#L20).

@Tomkourou Would you like to open a PR? :)

**Comment by davide-f** [comment]
For who will address this issue, it would be nice to add a "min" flag to specify to select the minimum number of clusters acceptable for the analysis

**Comment by Tomkourou** [comment]
> Nice catch! The fix should be easy, there is the need to add an elif in memory function to solve the problem, similarly to [how it was done in pypsa-eur](https://github.com/PyPSA/pypsa-eur/blob/e34cec427b38779ca49350d55bf98a60ed586ca1/rules/common.smk#L20).
> 
> @Tomkourou Would you like to open a PR? :)

Will do! And I like your suggestion :)

**Comment by davide-f** [comment]
@Tomkourou To add on the "min" option, the idea is to create the converse of "all".
"all" sets the number of clusters to match all buses in the network.
The proposed "min" option may identify the lowest number of clusters needed to run the optimization.

In particular, the minimum number of clusters depends on the subnetworks and country, and it is calculated in the following line as: `len(n.buses.groupby(["country", "sub_network"]).size())` or most likely just `len(n.buses.groupby(["country", "sub_network"]))` should work just fine.

https://github.com/pypsa-meets-earth/pypsa-earth/blob/6e6dbf609d2dd7a5978b92b8e4937cfe48bdb742/scripts/cluster_network.py#L305-L310

That can be useful for executing the smallest possible network of a region: if a single country is executed where the network is fully meshed, then that function may return 1.
If a single DC network is available, then that number increases to 2. If multiple countries are considered, the network is not fully meshed and/or multiple DC networks are available, that number increases.

To address this issue, beyond modifying the "memory" function as you just did, there is the need to revise the following code and add an elif to handle the "min" value:
https://github.com/pypsa-meets-earth/pypsa-earth/blob/6e6dbf609d2dd7a5978b92b8e4937cfe48bdb742/scripts/cluster_network.py#L683-L692

**Comment by davide-f** [comment]
Hello @Tomkourou :)
Wondering if you may have some comments :)

I was wondering that we could add also another option, such as: "Yflex", where Y denotes the number of maximum acceptable buses and the formula to calculate the number of clusters may be: `n_clusters = min(Y, len(n.buses))`

This would be nice for sensitivity over multiple countries: if a country doesn't have enough buses, we pick the number of buses instead.

insteast of "flex" different more easy-to-understand tags may be proposed.

What do you think?
