### ISSUE TITLE
Gas generators not being added to the network in add_electricity.

### ISSUE THREAD

**Issue by Tomkourou** [pz-max/pypsa-africa#820]
## Checklist

- [x] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

Running powerplantmatching for Indonesia returns a powerplant.csv with around 22GW of CCGT/OCGT. By the time it's added to the network in add_electricity only around 2GW is added to the network however. Going to do some debugging and see if I can find the cause. 

This might be related to issue https://github.com/pypsa-meets-earth/pypsa-earth/issues/407 and https://github.com/pypsa-meets-earth/pypsa-earth/issues/774

**Comment by Tomkourou** [comment]
This is the offending code : https://github.com/pypsa-meets-earth/pypsa-earth/blob/97b6b6d4c516595e505eb0c3e6bc1f8784630c12/scripts/add_electricity.py#L394-L396

It converts the carrier from natural gas to whatever was in the technology column. 

Here is an example of what the resulting carriers would be for natural gas after this line 

| carrier | value        |
|---------|--------------|
| CCGT    | 2940.000000  |
| LNG     | 1885.000000  |
| NG      | 2825.000000  |
| NG/D    | 412.000000   |
| NG/FO   | 100.000000   |
| Ng      | 10258.000000 |
| Ng/Fo   | 4289.000000  |

Anything that is not CCGT would then be ignored since it's not in the list of conventional_carriers.

**Comment by davide-f** [comment]
@Tomkourou amazing issue you spotted!
As a comment, I believe this issue if addressed may deserve higher priority to be merged than the one on population

**Comment by davide-f** [comment]
#824 ha
