### ISSUE TITLE
Add configuration file to drop dependency of world_iso and build_demand

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#827]
## Describe the feature you'd like to see

After https://github.com/pypsa-meets-earth/pypsa-earth/issues/814 is solved, an interesting feature is to decouple the overloading of world_iso and its use in build_demand to characterize which nc file to load by country.
I personally believe that it is safer to decouple the two dependencies:
- have 1 dictionary to clarify what countries are covered by each GEGIS nc file
- have 1 dictionary to store the country classification that we desire

Currently we are adopting a unique dictionary for both and that hinders the flexibility of defining the regional scope of the different entries

**Comment by Tomkourou** [comment]
Please assign me.

**Comment by davide-f** [comment]
Closed by #822
