### ISSUE TITLE
Improve code quality

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#828]
## Describe the feature you'd like to see

After revising https://github.com/pypsa-meets-earth/pypsa-earth/pull/823 it turns out that some functions may be improved to drop input paramters and clean the coding.
However, this is a tricky improvement and may lead to unwanted effects, so it is something to keep in mind, but not urgent

For examples, network scripts, e.g. simplify/cluster networks and those related to augmentation may be polished

**Comment by ekatef** [comment]
May be connected with #1197 and #1203

**Comment by davide-f** [comment]
We can close this... it is a too general comment
