### ISSUE TITLE
WSL issue

### ISSUE THREAD

**Issue by TomFer97** [pz-max/pypsa-africa#865]
## Checklist

- [ YES] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [YES ] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

*Please provide a description of what the bug is and add a minimal example/command for reproducing the bug.*
When I'm doing the first run: snakemake -j 1 solve_network -n
Seems that it need some information to complete the DAG

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*
I maybe did some error in the installation 

```bash
Set parameter Username
Academic license - for non-commercial use only - expires 2023-11-19
No parameters matching '_test' found
Building DAG of jobs...
Executing subworkflow pypsaearth.
C:\Users\tomma\anaconda3\envs\pypsa-earth\lib\site-packages\pypsa\networkclustering.py:16: UserWarning: The namespace `pypsa.networkclustering` is deprecated and will be removed in PyPSA v0.24. Please use `pypsa.clustering.spatial instead`.
  warnings.warn(
Config file configs/bundle_config.yaml is extended by additional config specified via the command line.
WARNING:snakemake.logging:Config file configs/bundle_config.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
WARNING:snakemake.logging:Building DAG of jobs...

MissingRuleException:
No rule to produce C:/Users/tomma/OneDrive/Desktop/PYPSA/pypsa-distribution/pypsa-earth/data/copernicus/PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif (if you use input functions make sure that they don't raise unexpected exceptions).
ERROR:snakemake.logging:MissingRuleException:
No rule to produce C:/Users/tomma/OneDrive/Desktop/PYPSA/pypsa-distribution/pypsa-earth/data/copernicus/PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif (if you use input functions make sure that they don't raise unexpected exceptions).
```

**Comment by ekatef** [comment]
Hey @TomFer97! Thanks for the report. As a double-check: have you specified retrieve_databundle: true in your config.yaml? That is needed for the first model run to fetch all the needed data.

**Comment by TomFer97** [comment]
Yes it's on true. In the [main] branch where I forked is true both in congi_tutorial.yaml (that I renamed) and config.yaml the original one

**Comment by davide-f** [comment]
Hello @TomFer97 !
Unfortunately that is a [known problem](https://github.com/pypsa-meets-earth/pypsa-distribution#installation): on windows, if you execute pypsa-distribution you need to use the wsl.
I see that you are using the standard prompt of windows that unfortunately leads to that error.
That is due to a known bug of snakemake that has not been fixed yet.
The same problem appears when using pypsa-earth-sec.
I recommend to install the wsl and execute all commands, including conda setup etc in the wsl shell

**Comment by davide-f** [comment]
Unfortunately I feel like this issue can be closed as it is not related to pypsa-earth
