### ISSUE TITLE
Retrieve databundle downloads bundles without checking file sizes

### ISSUE THREAD

**Issue by Emre-Yorat89** [pz-max/pypsa-africa#866]
## Checklist

- [ ] I am using the current [`main`](https://github.com/pypsa-meets-earth/pypsa-earth/tree/main) branch or the latest [release](https://github.com/pypsa-meets-earth/pypsa-earth/releases). Please indicate.
- [ ] I am running on an up-to-date [`pypsa-earth` environment](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

*Please provide a description of what the bug is and add a minimal example/command for reproducing the bug.*

## Error Message

*If applicable, paste any terminal output to help illustrating your problem.*
*In some cases it may also be useful to share your list of installed packages: `conda list`.*

```bash
<paste here>
```
Hello,
When running retrieve databundle script it downloads a cutout bundle that matches first. However, there could be also another bundle which has smaller size that satisfies the country requirement too. Therefore a size check of matched bundles would prevent burden on computer memory.

**Comment by ekatef** [comment]
Hello @Emre-Yorat89!
Thank you for adding the issue. My feeling is that addressing it would be very helpful if a particular country or region is of interest, which is a frequent use case.

As we have discussed, the current settings do not allow to download cutouts focused on the specific regions. A databundle is currently selected cover as much countries as possible from the provided countries list:

https://github.com/pypsa-meets-earth/pypsa-earth/blob/4f2ee93220e08a97e45a36142ac7696f68151e1f/scripts/retrieve_databundle_light.py#L459-L464

You suggest a selected data bundle should be as small as possible which sounds like a nice further development of the existing approach.

**Comment by Emre-Yorat89** [comment]
I think the issue can be solved by reordering cutout bundles according to their sizes in ascending manner in the config file. Since @yerbol-akhmetov has mentioned in the weekly developer meeting that the script downloads the first bundle that matches countries or areas of interest.

**Comment by ekatef** [comment]
> I think the issue can be solved by reordering cutout bundles according to their sizes in ascending manner in the config file. Since @yerbol-akhmetov has mentioned in the weekly developer meeting that the script downloads the first bundle that matches countries or areas of interest.

Hey @Emre-Yorat89, agree that it may be a quite elegant and straightforward solution. @davide-f what is you feeling about that?

**Comment by davide-f** [comment]
Hello!
Completely agree on the point.
To address this issue, there is the need to revise this function:
https://github.com/pypsa-meets-earth/pypsa-earth/blob/4f2ee93220e08a97e45a36142ac7696f68151e1f/scripts/retrieve_databundle_light.py#L449

Currently, when multiple cutouts contain all countries, a random one is picked.
The function works by creating the dictionary dict_n_matched that contains the numbers of matched countries (in values) for every cutout (in keys), we sort it and we pick as many bundles as needed till filling all countries.
To address the proposed issue, we should revise it and create a dataframe with two columns one being the number of matched countries by cutout (the current dictionary) and the second column being the number of countries by cutout.

Then, with pandas, we can sort the dataframe by the first column first and then the second column, and pick as many bundles as needed till matching the whole countries.

**Comment by davide-f** [comment]
This issue is now solved thanks to #911
