### ISSUE TITLE
fix readthedocs

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#876]
## Describe the Bug

Also addressed in PyPSA-Eur: https://github.com/PyPSA/pypsa-eur/pull/743
-- testing if graphviz/ the DAG graphs work is key

## Error Message

Problem in your project's configuration. Invalid configuration option "python.system_packages". This configuration key has been deprecated and removed. Refer to https://blog.readthedocs.com/drop-support-system-packages/ to read more about this change and how to upgrade your config file.

**Comment by davide-f** [comment]
Fixed by: 5ce3a150a8bb688f6b75ce1d8d6ed14e58d8a0c2
Closing
