### ISSUE TITLE
Avoid rebase?

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#887]
- PyPSA-Earth will lift all voltages before the optimization to a [base voltage e.g. 380kV](https://github.com/pypsa-meets-earth/pypsa-earth/blob/b205e83c3b631448a778e29257eed551790b9d5c/scripts/simplify_network.py#L8)

- Before the optimization, we rebase (see [function](https://github.com/pypsa-meets-earth/pypsa-earth/blob/b205e83c3b631448a778e29257eed551790b9d5c/scripts/base_network.py#L440-L468)) the voltage to different classes e.g. random example: 110-330kV is class 220kV, 330-550kV is class 380kV such that we can assign physical parameters from the [config.yaml](https://github.com/pypsa-meets-earth/pypsa-earth/blob/b205e83c3b631448a778e29257eed551790b9d5c/config.default.yaml#L165-L170). The question is if we can actually avoid it? I think what we need for that would be a line database with the linetype, **typical voltage** and physical parameters. PyPSA has already a [typical line database](https://pypsa.readthedocs.io/en/latest/components.html#line-types), which we could extend by a column "voltage" to allocate data automatically. My suggestion is to store this voltage column extended line-type database in PyPSA-Earth (one voltage has one line type) such that we can avoid the rebase.

**Comment by ekatef** [comment]
A there is detailed analysis of what effect does the voltage rebase have on the transmission capacity: https://github.com/GbotemiB/documentation/blob/it_de_comparison/notebooks/validation/it_de_comparison_notebook.ipynb 

A long story short, it looks like we overestimate transmission capacity when mapping lower voltage lines into lines with a higher "standard" threshold value. But it would be perfect to have a professional comment from the perspective of electrical engineering. @davide-f could you please give your view on that matter?

**Comment by ekatef** [comment]
Hello @pz-max!
I have a feeling that this issue could have been fixed with #999, which basically implements the ideas you sketched in this issue. Could you please check if any other points left?

**Comment by ekatef** [comment]
Closed as seems to be completed. Feel free to reopen if appropriate
