### ISSUE TITLE
Support input demand data with csv format

### ISSUE THREAD

**Issue by davide-f** [pz-max/pypsa-africa#987]
## Describe the feature you'd like to see

It would be nice to include automatic procedures to support csv dataformats as raw inputs for demand, beyond the default .nc files that we currently support.
A simple parser in build_demand may be done to support the two data formats.
We also have .csv files in the data folders that contain the same data as in .nc ones, we could investigate to potentially support both.

**Comment by ekatef** [comment]
A PR implementing this feature #995 is under testing now and seems to work well as far :)
